### ISSUE TITLE
Custom image not found

### ISSUE THREAD

**Issue by anhenrique** [mattieserver/netbox-topology-views#102]
Hi,

I'm trying to put custom images in my topology, but I'm not getting it, I've already changed the name of the images to the same as the slug. But when I look for the topology the image is not found, I don't know if I'm attaching the images in the wrong way, because I use netbox-docker.

Can you help me?

**Comment by mattieserver** [comment]
Hi,

How did you mount the images/folder in the netbox container?
You could mount the whole folder /opt/netbox/netbox/static/netbox_topology_views/img/ or just the images you need

**Comment by anhenrique** [comment]
Hi bro!

I added the images path as described in the netbox-docker repo:

**Custom Docker file**
The new Dockerfile-Plugins will allow us to build a new image with the necessary plugins installed.

FROM netboxcommunity/netbox:latest

COPY ./plugin_requirements.txt /
RUN /opt/netbox/venv/bin/pip install --no-warn-script-location -r /plugin_requirements.txt

# These lines are only needed if your plugin has its own static files.
COPY configuration/configuration.py /etc/netbox/config/configuration.py
RUN SECRET_KEY="dummy" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input

**my stuff:**
COPY img/ opt/netbox/netbox/static/netbox_topology_views/img/
RUN SECRET_KEY="dummy" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input

however I believe it is not correct, because I get the following error when compiling the container:

0 static files copied to '/opt/netbox/netbox/static', 481 unmodified.
Removing intermediate container 9fb1cf9fa8a1
 ---> 37eae7e88702

**Comment by mattieserver** [comment]
Hi,

Can you try to change the order in your own dockerfile?

so:
```
RUN SECRET_KEY="dummy" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input
COPY img/ /opt/netbox/netbox/static/netbox_topology_views/img/
```

Also note the **/** before /opt/netbox/netbox/static/netbox_topology_views/img/

**Comment by anhenrique** [comment]
YOU ARE THE MASTER!

Thanks friend, now it works
