### ISSUE TITLE
Installation for Netbox Docker

### ISSUE THREAD

**Issue by compgeniuses** [mattieserver/netbox-topology-views#104]
How can this plugin be installed on a Netbox Docker installation. it seems to assume all installations are non dockerized.

**Comment by mattieserver** [comment]
See the documentation from [netbox-docker](https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins)

**Comment by klaernie** [comment]
@compgeniuses In essence it boils down to build a new container, based on the official image, but installing the plugin:
```dockerfile
FROM ghcr.io/netbox-community/netbox
RUN set -x \
  && source /opt/netbox/venv/bin/activate \
  && SITEDIR=$(/opt/netbox/venv/bin/python3 -c 'import site; print(site.getsitepackages()[0])') \
  && pip install netbox-topology-views \
  && cp -r $SITEDIR/netbox_topology_views/static/netbox_topology_views /opt/netbox/netbox/static/ \
  && true
```

I did this very thing in https://github.com/klaernie/netbox-docker/
For my personal convenience I build it all directly using github actions and push the finished image to github's registry.
