### ISSUE TITLE
Changing background of visgraph

### ISSUE THREAD

**Issue by swgATpj** [mattieserver/netbox-topology-views#105]
Hey,

I'm working on a little project for my company, where I'm employed.
One of the last, missing features I want to implement is the background - it should just be an image of the site of the company (_without zoom-posibility_).
I've tried to edit the app.css and have added the attribute "background-color: green" (_just as a test_). But nothing happend.
So, how can I make it work?

Regards.

**Comment by mattieserver** [comment]
Hi,

The graph is created on a HTML Canvas, so you would need to set the background with something like this:

```js
graph_container = document.getElementById('visgraph');
graph_container.style.backgroundImage = "url('background.jpg')";
```

This will only work once the graph is created. (so after the network in drawn)

**Comment by swgATpj** [comment]
Thank you for the fast reply! :)
Do I have to put this into the app.js?

**Comment by mattieserver** [comment]
I currently don't plan on adding this to the actual project so you would need to run this in the browser console or use a browser plugin to execute this. (or fork/build the plugin yourself)

**Comment by mattieserver** [comment]
That would probably also work.
If you did the default install it should be at `/opt/netbox/venv/lib/python3.8/site-packages/netbox_topology_views/templates/netbox_topology_views/index.html`
Or else it is where you installed the package with pip.

Note that you should set the background-image on the canvas, with does not exist until you create the network.
So once you create the network inside  `<div id="visgraph" class=""></div>` there will be a canvas element on witch you can set the background.

**Comment by swgATpj** [comment]
Could you explain me where the canvas will be created? I want to change the width & height.
