### ISSUE TITLE
Devices even with saving not on the same position after loading/refreshig

### ISSUE THREAD

**Issue by swgATpj** [mattieserver/netbox-topology-views#117]
Heyy,

**at first:** initialLoad & saveCoordinates is set to true.

**To my issue:**
Every time I load the topology-view the nodes are a bit away of the position I set.

**For example:**
how the node is set: (.....[N].....)
how the node will be loaded: (...........[N].....)  

I'm hoping this is given you an overview about the issue.
Can this be fixed?

Best regards.

**Comment by dreng** [comment]
@swgATpj  I am not able to reproduce this issue. Are you using a custom field "coordinates"? If yes, please make this field visible, compare it's values between refreshes and report back.
