### ISSUE TITLE
Port numbers on topology

### ISSUE THREAD

**Issue by emintjeee** [mattieserver/netbox-topology-views#126]
is it possible to enable port numbers on the topology?

**Comment by swgATpj** [comment]
You mean which ports are enabled on the device?
That's possible, for that you have to edit the views-file.
Look there for more: [https://github.com/mattieserver/netbox-topology-views/issues/108](url)

**Comment by mattieserver** [comment]
If you hover over the cable you can see the port number.
Do you mean something else?

**Comment by jordanrvillarreal** [comment]
For me it would be very helpful if the port numbers would draw on the full diagrams as well. So I could get a full view, in one place.

**Comment by emintjeee** [comment]
Same for me.

**Comment by ukdyl94** [comment]
+1 for being able to see the interface on the topology without having to hover over the cable.

**Comment by dreng** [comment]
@emintjeee @jordanrvillarreal Would you please post a mockup of what exactly you propose? I can't imagine how we could place e.g. 48 port names of a switch in such a small space. I think the map would then become unreadable.

**Comment by Abyss777** [comment]
Hello

Port number is the only thing that stops me from migrating from other visualization plugin to yours.

Here is how it looks there:

![image](https://user-images.githubusercontent.com/5688080/215080015-b23d5af4-b417-46fb-987a-60360d304253.png)

**Comment by dreng** [comment]
That approach doesn't scale. See #71 and please note my previous post. You might want to redo the mockup with 50 ports on each switch and convince me.

Apart from that, we depend on what [vis-network](https://visjs.github.io/vis-network/examples/) is able to do.

**Comment by Abyss777** [comment]
You can make it switchable in case of many connections.

We do not have parallel 50 links. In case of different devices it does not look messy.

I know it's stone age, but we still use paper. We print schematics and issue them to field engineer. Or send images to contractors. We do not need Vlans on such schemes, just physical connections.

Looks like [vis-network](https://visjs.github.io/vis-network/examples/) doesn't support captions parallel to connections...

Thanks for response.

**Comment by dreng** [comment]
> We do not have parallel 50 links. In case of different devices it does not look messy.

You may don't. Most people do.

> I know it's stone age, but we still use paper. We print schematics and issue them to field engineer. Or send images to contractors.

Oh dear. That sounds like field engineers who are not able to abstract a list of connections into the real world.
 
> Looks like [vis-network](https://visjs.github.io/vis-network/examples/) doesn't support captions parallel to connections...

Yes, looks like. In that case we are powerless. Therefore I'm closing this proposal. Feel free to propose an FR at vis-network Github Repo. If they implement this, we can implement it aswell.

> Thanks for response

You're welcome.
