### ISSUE TITLE
'CircuitTermination' object has no attribute 'device'

### ISSUE THREAD

**Issue by cybarox** [mattieserver/netbox-topology-views#131]
## Plugin Info
NetBox Version: 3.2.5
Plugin Version: 2.0.1

## Debug Mode Output

Request Method: | GET
-- | --
Request URL | https://netbox.url/plugins/netbox_topology_views/?q=&hide_unconnected=on&site_id=28&cf_coordinates=
Django Version | 4.0.5
Exception Type | AttributeError 
Exception Value | 'CircuitTermination' object has no attribute 'device'
Exception Location | /opt/netbox/venv/lib/python3.8/site-packages/netbox_topology_views/views.py, line 142, in get_topology_data
Python Executable | /opt/netbox/venv/bin/python
Python Version | 3.8.10
Python Path | ['/opt/netbox/netbox/',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/opt/netbox/venv/lib/python3.8/site-packages']

## Plugin Config
```
PLUGINS_CONFIG  {
'netbox_topology_views': {
    'allow_coordinates_saving': True,
    'device_img': 'access-switch,core-switch,firewall,router,distribution-switch,backup,storage,wan-network,wireless-ap,server,switch,non-racked-devices,modem,patchpanel,usv,wlan,lte-router,lte-backup-router,datendose',
    'draw_default_layout': False,
    'enable_circuit_terminations': True,
    'end2end_connections': False,
    'ignore_cable_type': ['power outlet', 'power port'],
    'preselected_device_roles': [
        'Firewall',
        'Router',
        'Distribution Switch',
        'Core Switch',
        'Internal Switch',
        'Access Switch',
        'Server',
        'Storage',
        'Backup',
        'Wireless AP'
    ],
    'preselected_intermediate_dev_roles': [],
    'preselected_tags': []
    }
}
```

## Traceback
```
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/netbox_topology_views/views.py", line 277, in get
    topo_data = get_topology_data(self.queryset, hide_unconnected, intermediate_dev_role_ids, end2end_connections)
  File "/opt/netbox/venv/lib/python3.8/site-packages/netbox_topology_views/views.py", line 142, in get_topology_data
    elif link.termination_a.device.id in device_ids and link.termination_b.device.id in device_ids:

Exception Type: AttributeError at /plugins/netbox_topology_views/
Exception Value: 'CircuitTermination' object has no attribute 'device'
```

**Comment by mattieserver** [comment]
What version of the plugin is this?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Steven ***@***.***>
Sent: Friday, July 1, 2022 10:01:08 AM
To: mattieserver/netbox-topology-views ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mattieserver/netbox-topology-views] 'CircuitTermination' object has no attribute 'device' (Issue #131)


Debug Mode Output
Request Method: GET
Request URL     https://netbox.url/plugins/netbox_topology_views/?q=&hide_unconnected=on&site_id=28&cf_coordinates=
Django Version  4.0.5
Exception Type  AttributeError
Exception Value 'CircuitTermination' object has no attribute 'device'
Exception Location      /opt/netbox/venv/lib/python3.8/site-packages/netbox_topology_views/views.py, line 142, in get_topology_data
Python Executable       /opt/netbox/venv/bin/python
Python Version  3.8.10
Python Path     ['/opt/netbox/netbox/', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/opt/netbox/venv/lib/python3.8/site-packages']
Plugin Config

PLUGINS_CONFIG  {
'netbox_topology_views': {
    'allow_coordinates_saving': True,
    'device_img': 'access-switch,core-switch,firewall,router,distribution-switch,backup,storage,wan-network,wireless-ap,server,switch,non-racked-devices,modem,patchpanel,usv,wlan,lte-router,lte-backup-router,datendose',
    'draw_default_layout': False,
    'enable_circuit_terminations': True,
    'end2end_connections': False,
    'ignore_cable_type': ['power outlet', 'power port'],
    'preselected_device_roles': [
        'Firewall',
        'Router',
        'Distribution Switch',
        'Core Switch',
        'Internal Switch',
        'Access Switch',
        'Server',
        'Storage',
        'Backup',
        'Wireless AP'
    ],
    'preselected_intermediate_dev_roles': [],
    'preselected_tags': []
    }
}


Traceback

Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/netbox_topology_views/views.py", line 277, in get
    topo_data = get_topology_data(self.queryset, hide_unconnected, intermediate_dev_role_ids, end2end_connections)
  File "/opt/netbox/venv/lib/python3.8/site-packages/netbox_topology_views/views.py", line 142, in get_topology_data
    elif link.termination_a.device.id in device_ids and link.termination_b.device.id in device_ids:

Exception Type: AttributeError at /plugins/netbox_topology_views/
Exception Value: 'CircuitTermination' object has no attribute 'device'

**Comment by NULLProtogen** [comment]
I am also having this same issue. Setting 'enable_circuit_terminations': False got rid of the error but Topology also never draws the network. Not sure if that's related to this error but currently the plugin is not working.

**Comment by NULLProtogen** [comment]
I worked with a friend on this issue and we were able to add a sanity check to the code so that it does not error out.

Sanity check for the user does not follow a specific action.

Dev can add this to their code if they would like.

File: /opt/netbox/venv/lib/python3.8/site-packages/netbox_topology_views/views.py
Code added:
if not hasattr(link.termination_b, 'device'):
  print("CircuitTermination B Missing Device")
  continue

**Comment by mattieserver** [comment]
HI @NULLProtogen, at what line did you add this?
I will add this fix for the next release

**Comment by ekrichbaum** [comment]
Same error but only on some Sites. I didn't come up with the exact scenario. I didn't have the end2end setting but it didn't change anything for me.

**Comment by NULLProtogen** [comment]
@mattieserver Line 130.

![image](https://user-images.githubusercontent.com/77093988/182496351-1d3d8bd8-41d3-4077-9bc5-d58f2d874ec9.png)
