### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by maxzapp** [mattieserver/netbox-topology-views#132]
I installed yesterday an instance with 1.2.0.
Today i installed my second instance it seems that overnight a new version 2.0.1 has been released. But with this one i got 502 bad gateway

**Comment by mattieserver** [comment]
Hi,

What is the version of netbox?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: maxzapp ***@***.***>
Sent: Friday, July 1, 2022 11:53:52 AM
To: mattieserver/netbox-topology-views ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mattieserver/netbox-topology-views] 502 bad gateway (Issue #132)


I installed yesterday an instance with 1.2.0.
Today i installed my second instance it seems that overnight a new version 2.0.1 has been released. But with this one i got 502 bad gateway

**Comment by maxzapp** [comment]
Netbox 3.2.5
Ubuntu 20.4

**Comment by maxzapp** [comment]
Hi,
I found the reasons for my issues.

First in configuration.py the pluging has to be declared with netbox_topology_views instead of the real  plugin name  netbox-topologie-views

Second i had to use real root user to activate the venv environment and to install the plugins

Third  as i was installing my first two plugins i generated 2 separate PLUGIN = statements instead of putting all plugins in one like this PLUGINS = [´plugin1´,´plugin2´] 

Hope this will,help others as well.
