### ISSUE TITLE
Adding icon for backhauls

### ISSUE THREAD

**Issue by dmcken** [mattieserver/netbox-topology-views#143]
I would like an icon added for backhaul style devices, these are point-to-point wireless devices.

Something like this (taken from tessco's site):
<Image removed>

Not sure where the original icons where acquired from to get one created for a pull request.

**Comment by dreng** [comment]
As the posted image was taken from the website of [tessco](https://www.tessco.com/markets/transportation) and very likely violates copyright I decided to remove the image. The posted image can be visited [here](https://www.tessco.com/-/media/images/tesscocommerce/markets/transportation/product-category-icons/microwaveantennas_icon.ashx?la=en&hash=9E72D9AA10FB7EE34A746EEE53C448D832F69566).

**Comment by dreng** [comment]
Closed in favor of #240
