### ISSUE TITLE
Pypi package not up to date

### ISSUE THREAD

**Issue by dreng** [mattieserver/netbox-topology-views#146]
Latest release is 2.0.3 while pip upgrade shows 2.0.2. See https://pypi.org/project/netbox-topology-views/

**Comment by mattieserver** [comment]
Yeah, the v2.0.3 was indeed not published to pypi.
That release however does not have any real changes, just some updates to the metadata file for pypi.
So its not a real issue.

The latest beta release seems to just work fine.
