### ISSUE TITLE
v3 beta release extra import?

### ISSUE THREAD

**Issue by ThomasADavis** [mattieserver/netbox-topology-views#147]
```
[tdavis@mouse-r11 netbox_topology_views]$ grep tkint *
grep: api: Is a directory
grep: static: Is a directory
grep: static_dev: Is a directory
grep: templates: Is a directory
views.py:from tkinter.messagebox import NO
[tdavis@mouse-r11 netbox_topology_views]$ grep NO views.py 
from tkinter.messagebox import NO
[tdavis@mouse-r11 netbox_topology_views]$ grep NO */*
grep: static_dev/css: Is a directory
grep: static_dev/js: Is a directory
static_dev/yarn.lock:# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
grep: static/netbox_topology_views: Is a directory
grep: templates/netbox_topology_views: Is a directory
[tdavis@mouse-r11 netbox_topology_views]$ grep NO */*/*
grep: static/netbox_topology_views/css: Is a directory
grep: static/netbox_topology_views/img: Is a directory
grep: static/netbox_topology_views/js: Is a directory
[tdavis@mouse-r11 netbox_topology_views]$ 
```
I had to install python3-tk (container using debian) to get past this.. but I can't find any other reference to the import.

**Comment by mattieserver** [comment]
Strange, this should indeed not be needed.
Will look into it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: ThomasADavis ***@***.***>
Sent: Friday, September 2, 2022 12:53:07 AM
To: mattieserver/netbox-topology-views ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mattieserver/netbox-topology-views] v3 beta release extra import? (Issue #147)


***@***.*** netbox_topology_views]$ grep tkint *
grep: api: Is a directory
grep: static: Is a directory
grep: static_dev: Is a directory
grep: templates: Is a directory
views.py:from tkinter.messagebox import NO
***@***.*** netbox_topology_views]$ grep NO views.py
from tkinter.messagebox import NO
***@***.*** netbox_topology_views]$ grep NO */*
grep: static_dev/css: Is a directory
grep: static_dev/js: Is a directory
static_dev/yarn.lock:# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
grep: static/netbox_topology_views: Is a directory
grep: templates/netbox_topology_views: Is a directory
***@***.*** netbox_topology_views]$ grep NO */*/*
grep: static/netbox_topology_views/css: Is a directory
grep: static/netbox_topology_views/img: Is a directory
grep: static/netbox_topology_views/js: Is a directory
***@***.*** netbox_topology_views]$


I had to install python3-tk (container using debian) to get past this.. but I can't find any other reference to the import.

**Comment by peterbaumert** [comment]
https://github.com/mattieserver/netbox-topology-views/blob/318b8495b72209b2073976098743f249fdf25802/netbox_topology_views/views.py#L2


in this line its importing

**Comment by mattieserver** [comment]
v3.0.0-beta.2  is released to fix this.
