### ISSUE TITLE
vis is not defined

### ISSUE THREAD

**Issue by peterbaumert** [mattieserver/netbox-topology-views#150]
https://github.com/mattieserver/netbox-topology-views/blob/4ea2097429d4af22e8de11d40b4b495c5b837d6d/netbox_topology_views/static/netbox_topology_views/js/app.js#L1

Uncaught ReferenceError: vis is not defined
    at app.js:formatted:7:13
![image](https://user-images.githubusercontent.com/1212934/188154174-fbc8bf11-f6a1-484a-bbe2-319571cc2121.png)

**Comment by mattieserver** [comment]
Can you try to clear the browser cache and "hard reload" the js/css?

**Comment by peterbaumert** [comment]
Thanks, had to do collect static once more. sorry for bothering
