### ISSUE TITLE
Coordinates custom field usage...

### ISSUE THREAD

**Issue by Jorcha** [mattieserver/netbox-topology-views#154]
Netbox 3.3.0
Netbox-topology-viewes 3.0.0-beta.2 

Nice plugin you have done but have to ask this.

I have created Custom Field "coordinates" as text (ReadWrite mode off corse) to Circuits and Devices and leaved default value to null. 
When I move devices around in topology view nothing really happen and components don't stay there where I move them.

If I create Custom field with default value "500;500", all devices piles up in one point as expected and when I move them around they will stay there until view is refreshed when they pile up  into point 500;500 again.
Using other words: moving devices around topology view does not save moved point... Is that how it should be working?

**Comment by mattieserver** [comment]
Please check if you have set the `  'allow_coordinates_saving': True` setting in the netbox plugin settings.
Also check if you need the `'always_save_coordinates': True` setting.

**Comment by Jorcha** [comment]
Oh that was it. Should this information reside also where there is information that it's possible to use coordinate-custom field?

**Comment by mattieserver** [comment]
I will update the readme to make it clear that you have to include that option.
