### ISSUE TITLE
console connections missing

### ISSUE THREAD

**Issue by ekrichbaum** [mattieserver/netbox-topology-views#156]
Actually not sure when this stopped working, but just noticed it.

Netbox 3.3.2
netbox-topology-views 3.0.0 release
Python 3.10.6

Cables in general (ethernet), circuits, display, but console server to console connections disappeared.

![image](https://user-images.githubusercontent.com/11653069/189759496-f1800a8c-1de3-4ea6-8091-4c34e4ecfdc4.png)

Previously did display but I don't have a screen shot saved that I'm finding...

**Comment by mattieserver** [comment]
This will be in the next release
