### ISSUE TITLE
Feature: Download topology view as SVG

### ISSUE THREAD

**Issue by dreng** [mattieserver/netbox-topology-views#158]
Currently the download feature export the view as PNG. Names are sometimes not readable because they are too small and PNG is not scalable. Same Problem with large topologies where you can see just a bunch of devices but no details.

It would be nice if you where able to export as SVG.

**Comment by joaolucasmacedo** [comment]
I'm looking forward to see it.

**Comment by menckend** [comment]
Would be fantastic.

**Comment by dreng** [comment]
I would give up this feature in favour of #189 because it would be difficult to implement and draw.io already offers the feature.
