### ISSUE TITLE
Feature: Save filters

### ISSUE THREAD

**Issue by dreng** [mattieserver/netbox-topology-views#160]
It would be handy to be able to save different filter settings for later use.

**Comment by dreng** [comment]
This is on the NetBox roadmap for v3.4 already. See https://github.com/netbox-community/netbox/issues/9623. The implementation should be a piece of cake after v3.4 has been released.

**Comment by dreng** [comment]
As NetBox v3.4.1 is out, we are able to implement saved filters now.

**Comment by mattieserver** [comment]
I upgraded my Dev instance but did not see the saved filters show up when using the plugin. Will have to see if we need to make any changes.

**Comment by dreng** [comment]
> Will have to see if we need to make any changes.

We need to make changes for sure. I've had a look into it before. We must at least change the template. Unfortunately, there is one passage that I have not yet figured out. That's why I haven't yet assigned the issue to myself.
