### ISSUE TITLE
Hide Patch Panels

### ISSUE THREAD

**Issue by demesilva** [mattieserver/netbox-topology-views#162]
Is it possible to hide patch panels from the topology?

**Comment by mattieserver** [comment]
You will have to make sure the patch panel is not in the current filter. So if you have an device role or tag for patch panel make sure it is not selected in the filter.

**Comment by demesilva** [comment]
Sorry, but I didn't formulate the question correctly. I would like to display the connection between 2 devices that connect through patch panels, but hiding the patch panels. When I display the topology with the patch panels with the filter TAG filled in, all cables are displayed and not just the cables used in the connection in question between the devices. I tried to put TAG only on the cables that connect the 2 devices, but even so, the other cables that connect the 2 Patch Panels through their rear ports appear, which causes the topology to be polluted with many unused cables. One option would be to not show the cables from the rear ports that connect 2 patch panels when the front ports are without connections.

**Comment by mattieserver** [comment]
Ah yes, this is the same as #151.
Will see if i can add this back in.
