### ISSUE TITLE
Hiding cables connected to patch panel rear ports if the respective front port is unused

### ISSUE THREAD

**Issue by demesilva** [mattieserver/netbox-topology-views#173]
Hi. Is it possible to show in connections involving patch panels only the cables that have the front ports connected? Although in the filters I select the Hide Unconnected option, the topology is polluted with the cables between the rear ports of 2 patch panels that do not have their front ports connected to any device.

<img width="503" alt="2022-10-06 10_53_04-Topology Views _ NetBox" src="https://user-images.githubusercontent.com/4582740/194331241-e29ff500-5fe5-44c8-9edb-a6c0dd37b67f.png">

**Comment by joaolucasmacedo** [comment]
I'm looking forward to see that feature back.

**Comment by dreng** [comment]
I believe that this is first of all a question of definition. When cables are connected between rear ports, they are indeed connected. Logically speaking, there is no reason to leave out the cables.

If you define "connected" in such a way that there must be a link between an interface and a front port or between two front ports, that's a different story. In my personal case, the logic fits my needs and it also makes sense linguistically. So what you call "pollution" is desired in my scenario.

**Comment by demesilva** [comment]
I am already used to this view with connected cables, and implementing interface end-to-end connections brings a clean topology. Thank you for appreciating the question.

**Comment by dreng** [comment]
I understood that end-to-end connections are sufficient for you. Therefore I'm closing this feature request. Thank you for contributing.
