### ISSUE TITLE
No topology drawing after moving our netbox to docker

### ISSUE THREAD

**Issue by thr3swe** [mattieserver/netbox-topology-views#179]
Hi
We recently moved our netbox environment to docker. After the move, I of course wanted to install our beloved plugin topology views. Build and installation works fine, can't see any errors. But can't see anything in the view:

![image](https://user-images.githubusercontent.com/35501825/196972727-3a8d2d13-ab90-4c5a-824d-0905e513031e.png)
Using netbox version 3.3.5 and lates topology-views.

Followed this guide to install the plugin.
https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins

Just using 
PLUGINS = ["netbox_topology_views"]

in the configuration file.

The device roles are named according to the default value. "firewall" "access-switch" etc. It worked before we moved to docker and we are using the same database!

The http requests looks fine as well when looking at the log:
![image](https://user-images.githubusercontent.com/35501825/196973775-ceb05891-82e0-4526-ae5f-5cc7262fe2b0.png)

What am I doing wrong?

**Comment by thr3swe** [comment]
Anyone have any idea what's wrong? Can't figure it out.

**Comment by noziwatele** [comment]
Hi @thr3swe,
I have this issue on Netbox 3.3.8 on docker. The main network-topology-views window doesn't display anything, but I found that I could get a display after setting filters that include devices (e.g. Region, Site).

Not sure if this should be a bug still as I haven't used NTV before so not sure what the default view should look like.

**Comment by thr3swe** [comment]
It works for me now when I tried! Haven't changed anything.... Strange
