### ISSUE TITLE
Replace icons

### ISSUE THREAD

**Issue by joaolucasmacedo** [mattieserver/netbox-topology-views#187]
HI guys. I always replace almost all standar icons for the VRT Network equipment from Libreoffice.
They look better and it have more device roles. Maybe it is a good idea to @mattieserver take a look.

![router](https://user-images.githubusercontent.com/66760118/203312991-a75b31a2-32c3-4c62-af44-dbbb53156f4c.png)
![camera](https://user-images.githubusercontent.com/66760118/203313037-910e348e-4ef9-4138-b4a2-fe3122bc9e46.png)
![dvr](https://user-images.githubusercontent.com/66760118/203313070-789518d2-43a5-4fea-9ef3-129838c2649c.png)
![firewall](https://user-images.githubusercontent.com/66760118/203313101-6d80af86-032b-4778-b7c1-70e55388b94f.png)
![hub](https://user-images.githubusercontent.com/66760118/203313114-45507e1a-c562-4d32-aaae-4884c4b668d2.png)
![laptop](https://user-images.githubusercontent.com/66760118/203313139-6bfe2d0d-eec9-46e4-9cee-676cfa84f796.png)
![pc](https://user-images.githubusercontent.com/66760118/203313157-a754f7c9-a79b-4c58-acc7-eacdcc642657.png)
![pbx](https://user-images.githubusercontent.com/66760118/203313183-6225c7d6-ef27-497a-8439-4fee275ea4f0.png)
![printer](https://user-images.githubusercontent.com/66760118/203313215-9e82c53e-c2bd-436d-b77e-c2ca641c77bd.png)
![storage](https://user-images.githubusercontent.com/66760118/203313243-1ab38b2b-e8ad-4e59-b1fc-75e2de8490b4.png)
![wireless-ap](https://user-images.githubusercontent.com/66760118/203313268-47554ba2-1175-4e18-bdc1-3e4286042963.png)

**Comment by dreng** [comment]
Closed in favor of #240
