### ISSUE TITLE
draw.io/diagrams.net export

### ISSUE THREAD

**Issue by etfz** [mattieserver/netbox-topology-views#189]
If it's not too much effort, I think it would be cool to have the ability to export a topology to draw.io format.

https://app.diagrams.net/

**Comment by dreng** [comment]
This would be a very cool feature, though it's not a tiny bit of work. Some thoughts:

- draw.io files are described using XML, which makes it easy to implement
- We can write our own XML template and fill it with data like ID, X- and Y-Position
- Alternatively we could use their JS API (see https://jgraph.github.io/mxgraph/docs/js-api/files/shape/mxShape-js.html)
- draw.io uses edges (nodes in vis-network) and vertices (edges in vis-network), just like netbox-topology-views does
- We are bound to the shapes that draw.io provides. There seems to be no possibility to import your own shapes.
- draw.io supports many export file formats like PNG, SVG and PDF. That would make own implementations obsolete.

**Comment by andytruett** [comment]
Some information on draw.io Import/Export from https://drawio-app.com/draw-io-training-exercise-10-export-and-import/

> Import files
> 
> Of course, draw.io also offers an import function. You can import diagrams in the following formats:
> 
>     .xml (draw.io)
>     .gliffy (Gliffy)
>     .json (Lucidchart)
>     .vsdx (Visio)
>     .png (with XML)
>     .jpeg
>     .svg
>     .csv ([copy text from a .csv file to automatically create a diagram](https://drawio.link/importfromcsv))
> 
> Diagram editor: To import a file, go to File > Import from, then embed the file either from your Device or from a URL. In Confluence Data Center/Server, click File > Import, then select the file you want to import and click Import.
> 
> Board editor: To import a file, go to the Hamburger icon and then choose Import from, then select a Device or URL.
> 
> Import Visio and Gliffy diagrams
> 
>     Download our [Gliffy](https://github.com/jgraph/drawio-diagrams/blob/master/training-diagrams/Learndrawio.gliffy) and [Visio](https://github.com/jgraph/drawio-diagrams/blob/master/training-diagrams/HR%20Recruiting%20FlowchartB_start.vsdx) sample diagrams.
>     Open a new empty draw.io diagram.
>     Drag and drop the Gliffy diagram to your first diagram page.
>     Add a new page to your diagram, and import the vsdx file to this new page using drag and drop.
>     Save and close your diagram, and save the Confluence page.
> 
> Mass import Gliffy files
> 
> There is also a mass import function for Gliffy diagrams – you can convert all of the Gliffy diagrams within your Confluence intranet to draw.io with just a few clicks. Please have a look at the following links:
> 
>     [Gliffy Mass Import portal](https://drawio.link/gliffymigrationportal)
>     [Gliffy Mass Import guide](https://drawio.link/guidegliffymassimport)
> 
> Want to know more?
> 
> There are many more ways to export diagrams to use in documents or share online, and many different ways to import information into your draw.io diagram, as you can see by our long list of useful articles below.
> 
>     [Mass import guide to migrate Lucidchart diagrams over to draw.io](https://info.seibert-media.net/display/DRAWIO/Diagramming+in+Confluence+-+Mass+import+from+LucidChart+to+draw.io)
>     [Visio import for draw.io](https://drawio-app.com/diagramming-in-confluence-vsdx-import-for-draw-io/)
>     [Create draw.io diagrams from CSV](https://drawio-app.com/automatically-create-draw-io-diagrams-from-csv-files/)
>     [Import from CSV to draw.io diagrams ](https://drawio-app.com/import-from-csv-to-drawio/)
>     [Export diagrams as URLs](https://drawio-app.com/export-diagrams-as-urls/) – an entire diagram contained within the URL!
>     [Extracting the XML from draw.io’s compressed XML format](https://drawio-app.com/extracting-the-xml-from-mxfiles/)

**Comment by Vadims06** [comment]
Hi team,
I already did something similar, do you want to have a button to get XML file with L1 topology?

**Comment by dreng** [comment]
> Hi team, I already did something similar, do you want to have a button to get XML file with L1 topology?

Sounds great. May I assign this FR to you?
