### ISSUE TITLE
Alien icons

### ISSUE THREAD

**Issue by mhabiballa** [mattieserver/netbox-topology-views#192]
Hi,
I know its a primitive question to ask, but I followed the installation instructions and I've got the topology are shown but looks floating and the icons are at the defaults.
How to fix things,please.

![aliens](https://user-images.githubusercontent.com/114230054/205649467-3b4de1b0-f73a-4375-ba56-7d0886c7bb8f.png)

**Comment by mattieserver** [comment]
Hi,

The icon is used when the device role does not match any of the images that the plugin uses.
See https://github.com/mattieserver/netbox-topology-views#custom-images, you can upload your own images to that folder or rename some of the default ones.

**Comment by mhabiballa** [comment]
> Hi,
> 
> The icon is used when the device role does not match any of the images that the plugin uses. See https://github.com/mattieserver/netbox-topology-views#custom-images, you can upload your own images to that folder or rename some of the default ones.

Thank you. Turns out that I'm using different device roles slugs. when I change them back as to the existing imgs names, only routers images changed but not the switches. Also, > If you add your own image you also need to add the slug to the device_img setting. where can I find "device_img setting", please.
