### ISSUE TITLE
changes in topologies..

### ISSUE THREAD

**Issue by ThomasADavis** [mattieserver/netbox-topology-views#21]
in 0.4.0, you could generate topologies of power connections.  Very useful.

after version 0.4.1, this stopped working.

I'm trying to figure out what changed, and why the power connections no longer show up..

**Comment by mattieserver** [comment]
I added the "ignore_cable_type" option. This has a default option of 'power outlet,power port'.
If you want to see the power connections again you can change your settings to: 

`PLUGINS_CONFIG = {  
    'netbox_topology_views': {  
        'ignore_cable_type': ''
    }
}`

**Comment by ThomasADavis** [comment]
Got it.  Figures I missed something..
