### ISSUE TITLE
No installed app with label 'netbox_topology_views'

### ISSUE THREAD

**Issue by neilfrost1** [mattieserver/netbox-topology-views#224]
### NetBox version

v3.4.0

### Topology Views version

v3.1.1

### Steps to Reproduce

1. logged and su- to root
2. run source /opt/netbox/venv/bin/activate
3. type cd /opt/netbox/netbox
4. run pip3 install netbox-topology-views

### Expected Behavior

ability to run next section of install and have the plugin installed

### Observed Behavior

(venv) root@server1:/opt/netbox/netbox# pip3 install netbox-topology-views==3.1.1
Collecting netbox-topology-views==3.1.1
  Using cached netbox_topology_views-3.1.1-py3-none-any.whl (358 kB)
Installing collected packages: netbox-topology-views
Successfully installed netbox-topology-views-3.1.1
(venv) root@server1:/opt/netbox/netbox# python3 manage.py migrate netbox_topology_views
**CommandError: No installed app with label 'netbox_topology_views'.**

**Comment by mattieserver** [comment]
Do you have `PLUGINS = ["netbox_topology_views"]` in your `configuration.py`?

**Comment by neilfrost1** [comment]
yep, that was it. thanks - My first plugin install for Netbox... we all have to learn :) thanks for the speedy response
