### ISSUE TITLE
Netbox 3.4.1 not showing topology after upgrade - Uncaught ReferenceError: topology_data is not defined

### ISSUE THREAD

**Issue by fafavorit** [mattieserver/netbox-topology-views#228]
### NetBox version

v.3.4.1

### Topology Views version

v.3.1.1

### Steps to Reproduce

Hi,
I'm using Netbox in Docker. After upgrade to Netbox 3.4.1 and Topology view to 3.1.1 it stopped showing topology with following error in Chrome Console: Uncaught ReferenceError: topology_data is not defined. I can see new Topology Image changer so it seems that new plugin was deployed successfully into custom Docker Image.
I tried to clear browser cache, run colllect static manualy but nothing helped.

Any ideas except backup recovery? :)

thank you
Frantisek

### Expected Behavior

Show topology

### Observed Behavior

Uncaught ReferenceError: topology_data is not defined

**Comment by mattieserver** [comment]
Hi,

Can you share the dockerfile or at least the relevant parts for the install of the plugin?

We had some issues in the past with install in docker.

**Comment by fafavorit** [comment]
Hi,

here is configuration for create custom image:

```
cat /netbox/Dockerfile-Plugins
FROM netboxcommunity/netbox:latest

COPY ./plugin_requirements.txt /
RUN /opt/netbox/venv/bin/pip install  --no-warn-script-location -r /plugin_requirements.txt

# These lines are only required if your plugin has its own static files.
COPY configuration/configuration.py /etc/netbox/config/configuration.py
RUN SECRET_KEY="r8OwDznj!!dci#P9ghmRf******0AiPeDCQhKE+N_rClfWNj" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input
```

Frantisek

**Comment by mattieserver** [comment]
Strange, i just build the container the same way and it seems to work.

Just to make sure the version is correct, can you set the image version to `FROM netboxcommunity/netbox:v3.4.1`?

**Comment by fafavorit** [comment]
Hi,
 it is really strange. Change from netbox:latest to netbox:3.4.1 is working like a charm. But the 3.4.1 image was downloaded with netbox:latest too.  I have screenshots from Netbox which claims that it is v3.4.1. :D  Sorry I really don't know where is the difference, but great thanks to you! I would never try this change. Did you try to run it with :latest?

**Comment by mattieserver** [comment]
I tried with both the tags, but I had never pulled the latest imagine before this (on that machine). I know docker does not always pull the latest imagine by itself so maybe you got older version of the lastest imagine?
Another option could be the the image you pulled at that time was broken, i don't know the release process of docker-netbox but I could be that the latest tag is built against the master/main branch and there was a bug in one of the commits.

**Comment by Gakamine** [comment]
Hello,

I am still having the issue on V3.4.4 and still have the issue even rollbacking to v3.4.1.

I am wondering what could cause this error.

Could you help me please ? 🙂

**Comment by mattieserver** [comment]
> Hello,
> 
> I am still having the issue on V3.4.4 and still have the issue even rollbacking to v3.4.1.
> 
> I am wondering what could cause this error.
> 
> Could you help me please ? 🙂

Please open a new issue.
