### ISSUE TITLE
Devices in topology keep rotating

### ISSUE THREAD

**Issue by andreavivaldi** [mattieserver/netbox-topology-views#25]
Hi,
I've installed this plugin (version 0.4.8) on NetBox (version 2.8.4) and I have this strange behaviour: devices keep rotating without stop in a fixed position.
When I hit the search button (several time) they just stop.

Thanks for the support!

**Comment by mattieserver** [comment]
Thanks for reporting this.
I will look into what could cause this but i am not sure if i will be able to provide a solution as the graph itself is 'created' by a 3th party library

**Comment by andreavivaldi** [comment]
Thanks @mattieserver!
Which library do you use? Vis.js (my curiosity)?
Maybe it's worth a try upgrading the library? Let me know if you are able to reproduce the bug or if you need a hand (I'm not an expert developer but I can try)

**Comment by mattieserver** [comment]
It is indeed vis.js, or only the network part (vis-network).
I believe I used the latest version, unless they released a new version in the last week.

**Comment by mattieserver** [comment]
I managed to reproduce the bug, but only if i have set the custom field 'coordinates' for some devices.
Do you use that custom field?

**Comment by andreavivaldi** [comment]
Nope, this issue happens when I change the roles loaded by default and then hit search.
In fact, if I do not touch anything before hit search this bug doesn't show.
Then, to stop the rotation I have to hit search button several time.... this is very odd.
How about disabling physics in vis.js?

**Comment by mattieserver** [comment]
All devices are stacked on top of each other then. 
I will check if i can use another solver, now its 'forceAtlas2Based'.

**Comment by andreavivaldi** [comment]
The very odd fact is that is all working good until I touch form field... maybe some action to retrieve form field suggestion values make a conflict with the vis library?

**Comment by mattieserver** [comment]
I cannot change the physics to another type because then the coordinates within the plugin would be 'incorrect'.
So it seems like we are stuck.

**Comment by rkandilarov** [comment]
@mattieserver , perhaps button that enables/disables physics ones the initial solver phase.

**Comment by myhellone** [comment]
![obraz](https://user-images.githubusercontent.com/21089637/132368268-85054fde-0a12-40d3-b18f-0c1ae1bae4f9.png)
;/
