### ISSUE TITLE
Netbox 3.4.5 not showing topology - Uncaught ReferenceError: topology_data is not defined

### ISSUE THREAD

**Issue by Gakamine** [mattieserver/netbox-topology-views#259]
### NetBox version

v3.4.5

### Topology Views version

v3.2.1

### Steps to Reproduce

Upgrade Netbox to v3.4.5 (using a custom Netbox docker image to use Plugins)

### Expected Behavior

Display topology

### Observed Behavior

Uncaught ReferenceError: topology_data is not defined when looking in the console.
Downgrade to v3.4.1 does not seem to fix the issue.

**Comment by mattieserver** [comment]
Sorry for the late reply.
I assume you see the menu items in the nav bar?

**Comment by Gakamine** [comment]
Sorry for the late anwer. Here's my dockerfile:

```
FROM netboxcommunity/netbox:v3.4.5

ENV HTTP_PROXY=<proxy ip>
ENV HTTPS_PROXY=<proxy ip>

COPY plugin_requirements.txt /
RUN /opt/netbox/venv/bin/pip install --pre -I --no-warn-script-location -r /plugin_requirements.txt
COPY static /opt/netbox/netbox/static

COPY opt /opt
RUN SECRET_KEY=<secret key> /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input
```

Even cleaning the cache and rebuilding the image didn't solve the issue.
However, I changed the logo but after the update, it got reverted to the original netbox logo..

Any ideas? 😢

**Comment by dmcken** [comment]
Getting the same error atm, Firefox is still not loading it but Chrome is.

Dockerfile:
```
FROM netboxcommunity/netbox:3.4.5

COPY ./plugin_requirements.txt /
RUN /opt/netbox/venv/bin/pip install  --no-warn-script-location -r /plugin_requirements.txt

# These lines are only required if your plugin has its own static files.
COPY configuration/configuration.py /etc/netbox/config/configuration.py
RUN SECRET_KEY="dummy" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic 
```

Pretty much default but I hard-set the version so I control when upgrades happen.
