### ISSUE TITLE
Server Error: dcim.models.devices.DeviceRole.DoesNotExist when Device Roles are deleted with an icon assigned

### ISSUE THREAD

**Issue by borchert-nist** [mattieserver/netbox-topology-views#276]
### NetBox version

v3.4.7

### Topology Views version

v3.3.0

### Steps to Reproduce

1. Under "Devices" - "Device Roles", create a new "device-role" e.g. "TestRole"
2. Under "Topology Views" - "Images", Assign a new image to "TestRole"
3. Under "Devices" - "Device Roles", delete the created role "TestRole"
4. Select "Topology Views" - "Images" 

### Expected Behavior

The Screen Topology Views Images appears.

### Observed Behavior

A Server Error is thrown: <class 'dcim.models.devices.DeviceRole.DoesNotExist'>
DeviceRole matching query does not exist.

What happens is that the table "public.netbox_topology_views_roleimage" still contains the reference to the deleted role which cannot be found anymore because when deleting the role, the entry in the table "public.dcim_devicerole" is removed.

**Comment by borchert-nist** [comment]
At this point the only way to remove the server error is by manually removing the entry from the table public.netbox_topology_views_roleimage. A possible solution would be to only display elements that also exist in the public.dcim_devicerole table.

**Comment by dreng** [comment]
Thanks for reporting this bug. Your proposed solution might be the way to go. Of course deleting the database entry automatically if a role has been deleted would be a more elegant way.

**Comment by dreng** [comment]
I've had a quick look into the problem yesterday. While the easiest solution would be a foreign key, that would lead to another issue: The field does not only refer to the DeviceRole model. So a simple change of

https://github.com/mattieserver/netbox-topology-views/blob/86cb967d7098d4860b02db6d9764f1296ca319b5/netbox_topology_views/models.py#L38

into

`object_id = models.ForeignKey(DeviceRole, on_delete=models.CASCADE)`

would only do the trick if we seperate the RoleImage model into seperate models.

@ManiacMaxo Would you mind to take care of this bug? I'd assign you to the bug if that's okay for you.

**Comment by ManiacMaxo** [comment]
@dreng Ok, will look into it
