### ISSUE TITLE
Can't trace topo through non-selected device roles

### ISSUE THREAD

**Issue by garbled1** [mattieserver/netbox-topology-views#29]
If you have a setup like  switch->patch panel->switch, and you pick just "switches" for the device roles to show, you just see two switches floating unconnected.  They don't show up as connected unless you also pick the device role your patch panel is under.

While that might be desirable, if you have alot of patch panels, the resulting map is monstrous.

**Comment by mattieserver** [comment]
This is similar to #23 , but i can currently not provide a fix

**Comment by dreng** [comment]
I'd say it works like intended and is not related to #23. The switches aren't connected directly. If there's no physical cable between both devices, netbox-topology-views has got nothing to show either. You should use logical connections for what you want to see. This feature has been merged today in #188.
