### ISSUE TITLE
Location Centric (as opposed to filtered) topology views

### ISSUE THREAD

**Issue by dutchman80** [mattieserver/netbox-topology-views#293]
### NetBox version

v3.4.8

### Topology Views version

v3.4.0

### Feature type

New functionality

### Proposed functionality

When filtering topology by Location, or when clicking the "Topology" button in the Location view, show anything that's connected to the Location's Devices, within that Location's Site, along with the Location's Devices.  This behavior could be by default, or togglable with a checkbox.

This would depend on having the Topology button show up in Location views, the same way it shows up in the Site views now

### Use case

Normally, when filtering by Site, you just want to see the the devices in that Site.  However, when filtering by Location, you're often concerned with not just the devices within the Location, but any other devices within the Location's Site that those devices are connected to.

This would allow you to go to a Location, click the Topology button, and then see not only the Devices in that Location, but anything they're connected to outside the Location as well.  Extremely helpful for troubleshooting situations.

**Comment by dreng** [comment]
Thank you for your proposal. Did you notice the new "show neighbors" feature? If you go to the filter section, select a location and select "show cables", "show logical connections" and "show neighbors", is this the view you would expect for the proposed button?

**Comment by dreng** [comment]
Just want to add that this feature came with Netbox Topology Views v3.5.0. You have to upgrade first.

**Comment by dutchman80** [comment]
Amazing!  Yes, after upgrading to v3.5.1 I now see the "show neighbors" feature.  This is what I was imagining.

The only other ask would be to add the "Topology" button to Location views, the same way we currently have it in the Site views?

**Comment by dreng** [comment]
@dutchman80 Would you like to have a htmx popup just like it is on the Sites page or do you imagine a redirect to the "full" topology view page?

**Comment by dutchman80** [comment]
I think keeping it consistent with how the Sites page behaves makes intuitive sense so, yes, I'd like to see it as a pop up.
