### ISSUE TITLE
'CircuitTermination' object has no attribute 'device'

### ISSUE THREAD

**Issue by etfz** [mattieserver/netbox-topology-views#294]
### NetBox version

v3.5.1

### Topology Views version

v3.5.0

### Steps to Reproduce

1. Enable Show neighbors filter.
2. Display a topology including a device that connects to a circuit termination. (which is connected to a device in both ends)

### Expected Behavior

Topology to be displayed.

### Observed Behavior

```
<class 'AttributeError'>

'CircuitTermination' object has no attribute 'device'

Python version: 3.10.6
NetBox version: 3.5.1
```

**Comment by dreng** [comment]
Thank you for your bug report. I noticed this bug myself while working on the coordinate groups feature. Since a Circuit is not a device, it lacks a property we rely on. The bug is fixed in my branch already and will be commited with that new feature.
