### ISSUE TITLE
Add more topology view details - Edge label

### ISSUE THREAD

**Issue by tobicodesstuff** [mattieserver/netbox-topology-views#299]
### NetBox version

v3.5.1

### Topology Views version

v3.5.0

### Feature type

New functionality

### Proposed functionality

Add the possibility, for example via a checkbox 'Show cable name/label", to add the label of cables within the view. Similar to the cable pop-up which appears when hovering a cable.

### Use case

Further configuration possibility, also helpful when exporting the view to a picture.

### External dependencies

None

**Comment by dreng** [comment]
Hi @tobicodesstuff,

while it's not a big deal to add a label to cable and that might be useful, the labels overlap in some situations. That would lead to a desaster in terms of readability. Have a look at this very quick implementation:

![image](https://github.com/mattieserver/netbox-topology-views/assets/20901110/7542887f-1f71-46a8-a94c-c827714ecbb4)

**Comment by tobicodesstuff** [comment]
Hi @dreng,

your example is quite overloaded but I get your point. I was able to achieve a label on an edge and set the length of said edge to 300 not much more.

The visjs framework apparently does not support straight lines and such so such an example will probably always look this full.

**Comment by tobicodesstuff** [comment]
@dreng Do you the following could be achieved? Either together or separate:
- display a label as a combination of Cable Termination A interface and Cable Termination B interface or some similar concept? possibly with some configuration options?
- choose which labels to be displayed, it could be that when there are 10 edges I am interested in only a few or can customize it to my needs.

**Comment by dreng** [comment]
I'm not sure if I understand what you mean by "a label as a combination of Cable Termination A interface and Cable Termination B interface". A mockup would probably help.

Your second point "choose which labels to be displayed, it could be that when there are 10 edges I am interested in only a few or can customize it to my needs." sounds like programming hell and user experience chaos, to be honest.

The screenshot is a real world example btw. It's a patch panel fully connected to a switch. I see that there are tons of other examples where you have just one connection and where a label could be helpful. That said, we should be aware that labels look very chaotic and therefore are not helpful at all in much situations. We should also be aware that labels are always horizontal and not aligned to the cable, which make it worse in some situations.

**Comment by tobicodesstuff** [comment]
Scratch that, I think you are right and my suggestions weren't particularly great.
