### ISSUE TITLE
Toggle on Interface Descriptions / IP

### ISSUE THREAD

**Issue by darcynz** [mattieserver/netbox-topology-views#31]
Would be great to be able to toggle on the interface descriptions of the links on the map and the IP addresses on the devices. 

When looking it the map it would be great to see the information but be able to add it only when required to control clutter/information overload.

**Comment by dreng** [comment]
The problem here seems to be similar to #71. IP addresses are never bound to devices but to interfaces. A device can easily have 50+ interfaces, interfaces can theoretically have an infinite number of IP addresses. How would you visualize that without creating a completely disaster?
