### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by opensourcefan** [mattieserver/netbox-topology-views#314]
### NetBox version

v3.5.1

### Topology Views version

v3.5.0

### Steps to Reproduce

Topology Views / Individual Options

Show redundant Cable and `**Locigal**` Connection

### Expected Behavior

Logical

### Observed Behavior

Locigal

**Comment by opensourcefan** [comment]
Also at Topology Views / Topology / Filters

**Comment by dreng** [comment]
Hi @opensourcefan,
Thank you for reporting this! It has been fixed in #305 already and will be included in the next release.
