### ISSUE TITLE
Filter topology via URL Parameter

### ISSUE THREAD

**Issue by darcynz** [mattieserver/netbox-topology-views#32]
Firstly Topology tool is great, its excellent to be able to visualize netbox data. 

In order to make it more extensible, it would be great to able to add Parameters to URL to filter the map. 

etc
EG $NETBOX_URL/plugins/topology-views/?=sitename&role=Switch

From here a user could easily create custom links within netbox pages sites / devices to link to a related map.

**Comment by mattieserver** [comment]
Sounds interesting, I will look into this

**Comment by darcynz** [comment]
@mattieserver  was this impleted via #32? I saw this but could not get any filters to take in the URL..

**Comment by mattieserver** [comment]
Yes, if you draw a topology in the normal view and then click on the "share" icon you should get the full URL.

**Comment by darcynz** [comment]
Thanks works perfectly. Seriously Awesome. 
For any one using this, you can create a button for all sites with the following url:
https://netbox/plugins/topology-views/full?sites%5B%5D={{obj.id}}
