### ISSUE TITLE
Show Neighbors filter results in Server Error

### ISSUE THREAD

**Issue by stirosthegreat** [mattieserver/netbox-topology-views#321]
### NetBox version

3.5.2

### Topology Views version

3.5.0

### Steps to Reproduce

1. Create two devices that are connected on interfaces
2. Create a circuit where one side goes to a site and the other goes to another site with a device and interface connected
3. Open Topology View and choose the device without the circuit termination to view it's topology
4. set the "show cables" and "show circuit terminations" filters, this should work and show the circuit termination
5. set the "show neighbors" filter and this will result in the error "'CircuitTermination' object has no attribute 'device'"

### Expected Behavior

Expected the circuit termination to have a site on the other side for our provider network.

### Observed Behavior

<class 'AttributeError'>

'CircuitTermination' object has no attribute 'device'

Python version: 3.8.10
NetBox version: 3.5.2

**Comment by dreng** [comment]
Hi @stirosthegreat ,

Thank you for reporting this bug. It has already been fixed in the current development branch. Stay tuned for the next release.
