### ISSUE TITLE
Can we add rectangle box for sites, and specify the site code inside?

### ISSUE THREAD

**Issue by saifvs** [mattieserver/netbox-topology-views#329]
### NetBox version

3.4.5

### Topology Views version

3

### Feature type

New functionality

### Proposed functionality

Currently, when multiple sites are added and the view is zoomed out, the device names become hidden, making it difficult to identify the location of each site. Even using the CTRL+F search function doesn't help in this case.

To address this, I propose two improvements to enhance site visibility and labeling:

Add Rectangles Over Each Site:

When zoomed out, the device names become too small to read or disappear entirely. Adding rectangles over each site would help provide a visual indicator of their location, even when zoomed out. This would greatly assist users in quickly identifying the sites on the topology view.
Display Site Names:

Alongside the rectangles, it would be helpful to display the site codes or names within each rectangle. This way, even when zoomed out, users can still identify the site associated with each rectangle.
These changes would significantly improve the usability of NetBox Topology Views, especially for installations with a large number of sites and devices.

I have included two mock-up images to illustrate the suggested enhancements:
current view
![image](https://github.com/mattieserver/netbox-topology-views/assets/66313945/2dd38d90-dd72-4b7f-a734-5d619bba33a6)

Proposed View with Rectangles and Site Names:
![image](https://github.com/mattieserver/netbox-topology-views/assets/66313945/c9d9c0c9-ddda-476b-968b-7f9f69b43582)

### Use case

This will be useful when you want to find a specific site topology easily.

**Comment by dreng** [comment]
Although this sounds like a good idea at first, which can entail a little more structure in the topology, the picture presented seems a little too individual to me. Here the sites are grouped geographically. But that does not always have to be the case. The units can also be grouped according to logical aspects. The result would then possibly be that you get rectangles that include devices that do not belong to them at all.

**Comment by mattieserver** [comment]
The graph library has a group function that can allow you to set some properties for a group, so we could look into that. But since you can use coordinates or just render the graph dynamically the border you propose would not really work as in your screenshot.

**Comment by andrei-korshikov** [comment]
From my experience, it would be quite useful. I worked for a company with 600+ geographical locations, and in our schemes we used such rectangles, and it helped us a lot.

> set some properties for a group

Yep. The property for a group should be defined by a user. Site/tenant/region/etc - all of them can be useful for visual distinguishing in different situations.

>  the border you propose would not really work as in your screenshot

So we have to drag some devices manually, and borders will be repainted. I mean, at first we have rectangles overlapping each other in random manner, and then manually separate them by moving devices. Group selection would be nice feature for this (Ctrl+Click... click... click... or maybe select an area with mouse). And of course we need to save our work, some sort of saved views I would say. But it's a big step away from dynamic nature of Topology Views. Not sure if it should be done.

**Comment by etfz** [comment]
To expand on this idea, I would like to see filter options that allows drawing devices inside rack, location and site containers, and then being able to move these containers.

**Comment by dreng** [comment]
> The graph library has a group function that can allow you to set some properties for a group, so we could look into that.

That doesn't appear to be what it seems. I tinkered a bit with another approach which turned out to be very promising. I think, I will give it a try.

**Comment by dreng** [comment]
Somebody out there who want to test the code? See PR https://github.com/mattieserver/netbox-topology-views/pull/462.

**Comment by andrei-korshikov** [comment]
I will definitely try it, but in a week or so, sorry for delay. And thank you for your work!

**Comment by dreng** [comment]
Hi Andrei,

thanks for helping out. I'm giving it another try at this moment and it works out pretty well. So no worries. I think it has been too late in the evening yesterday and I did some things completely wrong.

I think, the code will be done by the end of the day.
