### ISSUE TITLE
ability to place nodes on a map

### ISSUE THREAD

**Issue by laimaretto** [mattieserver/netbox-topology-views#330]
### NetBox version

v3.5-2.6.1

### Topology Views version

v3.5

### Feature type

New functionality

### Proposed functionality

Each device needs to be linked to a site. When creating a site, there is also the possibility to document LAT and LONG. The idea would be to grab that information to allow the nodes to be placed on a map, probably by means of [folium](https://pypi.org/project/folium/).

### Use case

Once this is implemented, there is an added value for example when engineers need to plan a visit to several sites. Having those on a map helps on the decision.
Other use case is distance between nodes. At first, the distance could be linear, so one could estimate, for example, fiber optics or microwaves attenuation due to distance between nodes.
For sure there will be other use cases, but this are the ones that I need to deal with from time to time.

### External dependencies

You could use [folium](https://pypi.org/project/folium/) which is a Python lib that practically solves this use if you can provide LAT and LON per each node.

**Comment by mattieserver** [comment]
This has been requested a lot but will not be added in this plugin.
