### ISSUE TITLE
Blank Main PAge

### ISSUE THREAD

**Issue by jfreak53** [mattieserver/netbox-topology-views#338]
### NetBox version

3.5.4

### Topology Views version

3.5.0

### Steps to Reproduce

When I click on Topology, it loads, but blank. I've checked console log in browser, its blank, no errors. I've also cleared cache. Screenshot below:

https://cdn.microtronix-tech.com/imgs/firefox_2E7ustmJkT.png

### Expected Behavior

Should show me topology of links

### Observed Behavior

Blank

**Comment by mattieserver** [comment]
Did you define any filters? I don't see the search terms in the ui.
