### ISSUE TITLE
More icons..

### ISSUE THREAD

**Issue by ThomasADavis** [mattieserver/netbox-topology-views#34]
Where did you get the icon set from?  I'd like to add more icons from that set if possible.

**Comment by mattieserver** [comment]
A coworker provided them, so i don't know the real source.
However it seems like they are based of: https://www.cisco.com/c/en/us/about/brand-center/network-topology-icons.html

**Comment by ThomasADavis** [comment]
Does this support use of SVG based icons?

**Comment by mattieserver** [comment]
only PNG images will work
