### ISSUE TITLE
Version 3.6 does not work with netbox 3.4.x because of migration dependencies

### ISSUE THREAD

**Issue by kkthxbye-code** [mattieserver/netbox-topology-views#340]
### NetBox version

v.3.4.10

### Topology Views version

3.6.0b2

### Steps to Reproduce

1. `pip install netbox-topology-views==3.6.0b2`
2. Add plugin in configuration.py
3. Run migrations `python netbox/manage.py migrate`

### Expected Behavior

Plugin should install.

### Observed Behavior

```
django.db.migrations.exceptions.NodeNotFoundError: Migration netbox_topology_views.0004_coordinategroup_coordinate dependencies reference nonexistent parent node ('dcim', '0171_cabletermination_change_logging')
```

The reason is because the `0004_coordinategroup_coordinate` migration depends on two migrations only present in netbox v3.5+.

https://github.com/mattieserver/netbox-topology-views/blob/daf35c097d2bb53d32242ffc4b71a38e165e056b/netbox_topology_views/migrations/0004_coordinategroup_coordinate.py#L11-L15

Now there might be a good reason for this, I was just unable to find it. I tried removing the two dependencies and the migrations ran fine and everything seems to work from a quick glance. If the dependencies are indeed there by mistake, would it be possible to remove them to make netbox-topology-views support netbox v3.4.x?

**Comment by dreng** [comment]
Hi @kkthxbye-code ,

Thanks for reporting this. Unfortunately no, there's no good reason for this. We need to change the migration script.
