### ISSUE TITLE
Ability to configure topology settings displayed in site overview page

### ISSUE THREAD

**Issue by you-like-ice-cream** [mattieserver/netbox-topology-views#341]
### NetBox version

v3.5.3

### Topology Views version

v3.5.0

### Feature type

New functionality

### Proposed functionality

It would be good to be able to configure the topology created in the site overview page (Organisation > Sites > Site n > Topology) so that we can choose to enable logical connections and disable physical connections.

As is, my fibre connections between switches and some cat6 connections are physically connected via patch panels which are not being treated as physical connections and this results in very few devices being shown in the site overview topology.

### Use case

Allow for a more complete topology view in the sites overview page.

**Comment by dreng** [comment]
This proposal would also include locations (#293).

Would it be sufficient to use the current individual options? Otherwise we need to define individual options for three kinds of topology views which doesn't seem to me to be a good design.

**Comment by you-like-ice-cream** [comment]
Hi Dreng, I've noticed that I made a small boo-boo in my configuration and that the site topology improves when I removed the filtered port types in the Individual Options (I was filtering front ports/back ports) but still if these views could be generated based on the settings in the Individual Options page that would make it much better, I would like to have the sites topology view show only the logical connections rather than physical and then I can filter out the patch panels that connect certain devices.

Cheers
