### ISSUE TITLE
'ProviderNetwork' object has no attribute 'device'

### ISSUE THREAD

**Issue by SimonFischer04** [mattieserver/netbox-topology-views#350]
### NetBox version

v3.5.6

### Topology Views version

v3.6.1

### Steps to Reproduce

1. create a circuit including termination (z side in my case) to provider network
2. open the "Topology" view

### Expected Behavior

Topology to be displayed.

### Observed Behavior

```
<class 'AttributeError'>

'ProviderNetwork' object has no attribute 'device'

Python version: 3.10.6
NetBox version: 3.5.6
```

**Comment by SimonFischer04** [comment]
Seems to be related to: https://github.com/mattieserver/netbox-topology-views/issues/294 as this was also the issue for me before updating to v3.6

**Comment by dreng** [comment]
Please provide the **exact** steps to reproduce and your **exact** settings for the topology view as I am not able to reproduce this.

**Comment by SimonFischer04** [comment]
narrowed it down to: 
Settings (only this two enabled still results in the issue):
- "Show Logical Connections" AND
- "Show Neighbors"
if I disable either one the issue is resolved.

The circuit I have:
![Screenshot_20230711_184938](https://github.com/mattieserver/netbox-topology-views/assets/20473239/e229ffcc-4b84-4a5f-97ad-c9c6ec59c306)
![Screenshot_20230711_185133](https://github.com/mattieserver/netbox-topology-views/assets/20473239/34d51b0f-40bd-4445-b845-b9904d84f613)
![Screenshot_20230711_185217](https://github.com/mattieserver/netbox-topology-views/assets/20473239/484a6f9d-c40f-4a1d-9cf4-befcfa673e5c)

**Comment by dreng** [comment]
The problem lies in views.py, line 355. A device.id is expected, which is true for e.g. Interfaces but not for ProviderNetworks.

`device_ids.append(connected_endpoint.device.id)`

We need to check if connected_endpoint is of a supported class type.
