### ISSUE TITLE
Allow Coordinate Groups to be saved in the saved filters

### ISSUE THREAD

**Issue by mattieserver** [mattieserver/netbox-topology-views#352]
### NetBox version

3.5.6

### Topology Views version

3.6.1

### Feature type

New functionality

### Proposed functionality

Allow Coordinate Groups to be saved in the saved filters

### Use case

Allow Coordinate Groups to be saved in the saved filters

**Comment by dreng** [comment]
This is a general problem and not specific to coordinate groups. See #236

**Comment by mattieserver** [comment]
Follow up in https://github.com/mattieserver/netbox-topology-views/issues/236
