### ISSUE TITLE
Better Image Export for large Topologies

### ISSUE THREAD

**Issue by m384wwn** [mattieserver/netbox-topology-views#36]
As I understand it the only way to export images is to right click on the visualisation then click "save image as". 

This works great for a small number of nodes but for example we have a site with 800+ cables and i can either zoom in and save an image of just a few nodes or zoom out and save an image which does not have enough resolution to be legible.

Maybe a "save full topology as image" feature which then exports the entire thing at a customizable resolution.

**Comment by mattieserver** [comment]
This is already in the code but not available in the pip package, next release you will see a download button.
However this has not yet been tested on a large data set.
