### ISSUE TITLE
Display interface names on topology view

### ISSUE THREAD

**Issue by bradley-rose** [mattieserver/netbox-topology-views#363]
### NetBox version

v3.5.7

### Topology Views version

v3.6.2

### Feature type

New functionality

### Proposed functionality

Include option to display interface names on the topology view. Realistically, I'd like to see the interface names on the topology so that I could export the PNGs and save them to a backup directory for offline viewing.

### Use case

At-a-glance information about interface connections to devices. This would allow:

- More efficient changes of cabling and cable tracing at-a-glance
- Easy export-to-PNG for offline viewing that includes the interface labels.

**Comment by dreng** [comment]
Hi Bradley,

this has been proposed and discussed a few times before. See #300, #126 and #71 for the reasons why the proposal will not be implemented.

**Comment by bradley-rose** [comment]
Hey @dreng, thanks for the reply. I was hoping I had finally found a replacement for Visio, but without interface labeling available, I don't know if there's much value to these topology views to me. I completely understand that this is simply a limitation of the framework that this plugin is built on-top of.

It's a great feature and the plugin certainly looks great, but I am still wanting to ensure we have diagrams that can be accessed in the case of a DR scenario where NetBox could potentially become inaccessible. 

If anyone else that comes across this has any ideas for how to utilize the information in Netbox to dynamically update network diagrams with interface labeling, I'd love that.

**Comment by SureimAndreas** [comment]
I made a greasemonkey script to add this functionality, Maybe this is something you could consider adding as a native function. Kind of a middle way of not showing it as standard, but possibility to add it were you want it. @dreng 

Possibility to right click links to add the connection of only those you want to see. (Be able to move and also angle them)

https://github.com/SureimAndreas/netbox-topology-views---Add-connection-texts-to-links/

**Comment by HasakiGit** [comment]
Can u tell, how install this .js script?
