### ISSUE TITLE
Filter by Region

### ISSUE THREAD

**Issue by darcynz** [mattieserver/netbox-topology-views#37]
As per the other filter by site, would be great to be able to filter by a region.

**Comment by mattieserver** [comment]
Note that sites are linked to regions and when you select a region you will not see sites that are not within that region.

**Comment by sdktr** [comment]
Cool! Does this filter support nested regions as well? So when selecting a region that has childs, will the childs sites by included or not?

**Comment by mattieserver** [comment]
Feature was added a while ago, nested regions are not supported for now.
