### ISSUE TITLE
Errors when install module 

### ISSUE THREAD

**Issue by SerhiiZahuba** [mattieserver/netbox-topology-views#373]
### NetBox version

v3.6.0

### Topology Views version

v3.7.0

### Steps to Reproduce

I installed the new version of the module and netbox 3.6.0 but I see an error that the module wants a version lower than 3.6.0

### Expected Behavior

Successful installation

### Observed Behavior

Installing the module with an error.

![image](https://github.com/mattieserver/netbox-topology-views/assets/36307887/11e06a35-abd8-4e34-a8f1-4aff2f9a1e84)

**Comment by mattieserver** [comment]
This is not an error with this plugin?

**Comment by SerhiiZahuba** [comment]
sorry My mistake. I got confused in the plugins.

**Comment by SerhiiZahuba** [comment]
sorry My mistake. I got confused in the plugins.
