### ISSUE TITLE
Server error when opening admin/current config: "'NoneType' object has no attribute '_meta'"

### ISSUE THREAD

**Issue by haki99** [mattieserver/netbox-topology-views#374]
### NetBox version

v3.6.0

### Topology Views version

v3.7.0

### Steps to Reproduce

1. Install netbox v3.6.0 and topology plugin v3.7.0
2. Click on admin/current config
3. Server error: 'NoneType' object has no attribute '_meta'

### Expected Behavior

The page is loaded successfully.

### Observed Behavior

The following server error occurs:
![image](https://github.com/mattieserver/netbox-topology-views/assets/51157531/e9b1bce0-ab55-4750-b825-8bbb2e2eb8c7)

**Comment by Azmodeszer** [comment]
Can confirm.

**Comment by mattieserver** [comment]
I just did a clean install without the plugin and i still have the error. It might be best that you create a issue in the official netbox repo since it looks like this might not be related to the plugin itself.

**Comment by mattieserver** [comment]
Looks like it is already fixed in netbox v3.6.1: https://github.com/netbox-community/netbox/issues/13622
