### ISSUE TITLE
Unable to save images on latest version (v3.7.0)

### ISSUE THREAD

**Issue by mattieserver** [mattieserver/netbox-topology-views#375]
### NetBox version

v3.6.0

### Topology Views version

v3.7.0

### Steps to Reproduce

1. Go to the images tab under preferences
2. Select a role and change the image
3. the following error is seen: 😢 {"error": "'str' object has no attribute 'removeprefix'", "exception": "AttributeError", "netbox_version": "3.6.1", "python_version": "3.8.10"}

### Expected Behavior

You should be able to save the image

### Observed Behavior

😢 {"error": "'str' object has no attribute 'removeprefix'", "exception": "AttributeError", "netbox_version": "3.6.1", "python_version": "3.8.10"}

**Comment by NetworkSeb** [comment]
+1

**Comment by bitcollector1** [comment]
+1 here was well

**Comment by dreng** [comment]
Is this still an issue? I tried to reproduce this bug but everything went fine. NetBox 3.6.4-dev and NTV 3.7.0-dev.

**Comment by mattieserver** [comment]
> Is this still an issue? I tried to reproduce this bug but everything went fine. NetBox 3.6.4-dev and NTV 3.7.0-dev.

yes, we have this currently on our prod & acc netbox servers.

**Comment by danpetraru** [comment]
nb 3.6.2 and latest version of the plugin - still an issue

**Comment by davijls9** [comment]
I still have the problem too.

**Comment by dreng** [comment]
I am not able to reproduce this bug because I am using Python 3.9.2. The built-in function removeprefix() was introduced in Python 3.9.0. Updating Python should solve the issue.

We worked around this problem in utils.py, line 20 and 39. But there are 2 other occurrences in api/views.py.
