### ISSUE TITLE
Site Map

### ISSUE THREAD

**Issue by gbrownie** [mattieserver/netbox-topology-views#392]
### NetBox version

v3.6.3

### Topology Views version

v3.7.0

### Feature type

New functionality

### Proposed functionality

Since devices can already save positions, it would be useful to be able to put a site map image in the background. 

### Use case

Site maps would allow for tracking of network devices in physical locations (APs, rack locations, etc.)

### External dependencies

Image processing is done already with the device icons so probably not but I'm not sure.

**Comment by dreng** [comment]
See #388
