### ISSUE TITLE
preselected_device_roles should be a list, not a comma separated string

### ISSUE THREAD

**Issue by ypid** [mattieserver/netbox-topology-views#42]
`preselected_device_roles` and others are split on comma. This looks very random to me when we can just pass proper data structures to the plugin. I just tested this with Netbox 2.8.7, works nicely. The file that does the split is https://github.com/mattieserver/netbox-topology-views/blob/master/netbox_topology_views/api/views.py

What do you think?

Thanks for the plugin btw :+1:

**Comment by mattieserver** [comment]
Yeah, it should indeed be cleaner if it was just a normal array.
I will change it but people that used custom settings will have to change their settings.

**Comment by ypid** [comment]
> I will change it but people that used custom settings will have to change their settings.

Not necessarily, the variable type could be checked :wink:
