### ISSUE TITLE
Netbox API Tokens Don't Authenticate API Endpoints

### ISSUE THREAD

**Issue by Sejo9** [mattieserver/netbox-topology-views#422]
### NetBox version

v3.6.3

### Topology Views version

v3.8.0

### Steps to Reproduce

1. Create an API token for the desired user
2. Create an API Request to the netbox-topology-views' XML Export endpoint found on the REST API endpoint page using either POSTMAN or any programming language of your choice
3. Include API token as a header (Authorization)
4. Include query params for the options available 
5. Send the request

### Expected Behavior

Returns an XML response of the created topology

### Observed Behavior

Returns the netbox login page (HTML) as a response

**Comment by Sejo9** [comment]
@mattieserver Has this been resolved. Any response would be much appreciated. Thanks for your great work.

**Comment by mattieserver** [comment]
Hi,

I started working on it but then I had to focus on other things.

In two weeks I have some time of so I might be able to look at it then.

**Comment by Sejo9** [comment]
Alright. Thanks for the feedback

**Comment by BridgeCross** [comment]
Hi, please i ran into this same issue. Has it been fixed or are you still working on it?

**Comment by Sejo9** [comment]
@mattieserver Was a fix for this included in the recent release? Or tested with the recent release?

**Comment by dreng** [comment]
> @mattieserver Was a fix for this included in the recent release? Or tested with the recent release?

Nope

**Comment by Sejo9** [comment]
Alright
