### ISSUE TITLE
add filter field rack

### ISSUE THREAD

**Issue by voorspoatos** [mattieserver/netbox-topology-views#428]
### NetBox version

v3.3.0

### Topology Views version

V3.3.0

### Feature type

New functionality

### Proposed functionality

In the filter Tab, add the Rack field to be able to search items in this rack

### Use case

be able to search all items in this rack

**Comment by dreng** [comment]
Thank you for contributing to this plugin. While your proposal is reasonable, it has been implemented already. Please update to a newer version if you really don't find this filter.
