### ISSUE TITLE
Plugin does not work in v3.7-beta1

### ISSUE THREAD

**Issue by PaulR282** [mattieserver/netbox-topology-views#430]
### NetBox version

v3.7-beta1

### Topology Views version

v3.8.1

### Steps to Reproduce

Try to update netbox to v3.7-beta1 with the plugin

### Expected Behavior

Netbox should start

### Observed Behavior

```
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/plugins/netbox-topology-views/netbox_topology_views/models.py", line 13, in <module>
    from netbox.models.features import (
ImportError: cannot import name 'WebhooksMixin' from 'netbox.models.features' (/opt/netbox/netbox/netbox/models/features.py)
```

**Comment by ekrichbaum** [comment]
I didn't load the beta yet but that is where the import lives and I don't see it changed in the updates post 3.6.6.  Was that error from the upgrade.sh script during install or from attempting to start netbox?  Was the plugin installed to the venv because the path looks native and not part of the venv?

Activate the venv manually and install the plugin
```
cd /opt/netbox
source venv/bin/activate
pip install netbox-topology-views
```

and then try to run it.  or add it to the local_requirements.txt and run the upgrade script to recreate the venv.

**Comment by dreng** [comment]
This is not a problem in my dev environment. Is this still a problem? Can you react on @ekrichbaum's post, please?

**Comment by PaulR282** [comment]
> I didn't load the beta yet but that is where the import lives and I don't see it changed in the updates post 3.6.6.  Was that error from the upgrade.sh script during install or from attempting to start netbox?  Was the plugin installed to the venv because the path looks native and not part of the venv?
> 
> Activate the venv manually and install the plugin
> ```
> cd /opt/netbox
> source venv/bin/activate
> pip install netbox-topology-views
> ```
> 
> and then try to run it.  or add it to the local_requirements.txt and run the upgrade script to recreate the venv.

Sorry for the late reply, I wasn't at work since. We use netbox in a docker container so the message was just the output of the container. I'm currently not sure if I have updated the plugin to v3.8.1. I will check and get back to you tomorrow.

**Comment by PaulR282** [comment]
It is v3.8.1
We build our own image for the docker container. The plugin is installed as this:
```
COPY ./plugins /plugins/
COPY --chown=0:0 --chmod=755 plugins/netbox-topology-views/netbox_topology_views/static/netbox_topology_views /opt/netbox/netbox/static/
RUN /opt/netbox/venv/bin/pip install --editable /plugins/netbox-topology-views
```
It was working well until I wanted to test the new beta.

**Comment by ThomasADavis** [comment]
I'm seeing this too, it's because in v3.7, the WebHookMixin will become EventRulesMixin.

A quick testing fix is to use `git+https://github.com/ThomasADavis/netbox-topology-views.git` in your plugin_requirements file, instead of the straight `netbox-topolog-views`.  It works then with the v3.7-beta1.

**Comment by ekrichbaum** [comment]
You should submit that change as a PR so we can get it wrapped in along with a check and version set for >3.7 needs plugin 1.x.x

**Comment by dreng** [comment]
> I'm seeing this too, it's because in v3.7, the WebHookMixin will become EventRulesMixin.
> 
> A quick testing fix is to use `git+https://github.com/ThomasADavis/netbox-topology-views.git` in your plugin_requirements file, instead of the straight `netbox-topolog-views`. It works then with the v3.7-beta1.

Thomas, a PR is highly appreciated. Would you like to be assigned to this bug?

**Comment by ThomasADavis** [comment]
I would like to, but I'm out of the office till Jan 2nd..

**Comment by dreng** [comment]
That's not a problem. I'll assign you. Thanks in advance.

**Comment by mlazzarotto** [comment]
Using the git repo worked, although I had to add `apt update` `apt install -y git` in the `Dockerfile-Plugins` in order for Docker to install the plugin.
Just as reminder, the PyPI.org version is still the old one.

**Comment by mattieserver** [comment]
you can use 'netbox-topology-views==3.9b1' in the local_requirements.txt to test with version v3.7 (of netbox)

**Comment by mattieserver** [comment]
PyPi show the version as a pre-release, since it is marked as beta/pre-release on github.
You should see it at: https://pypi.org/project/netbox-topology-views/3.9b1/#history

**Comment by mlazzarotto** [comment]
> you can use 'netbox-topology-views==3.9b1' in the local_requirements.txt to test with version v3.7 (of netbox)

Like a charm! Thank you🙂
