### ISSUE TITLE
Images Link not work

### ISSUE THREAD

**Issue by fbaschin** [mattieserver/netbox-topology-views#434]
### NetBox version

3.6.6

### Topology Views version

3.8.1

### Steps to Reproduce

Click on Image Link not work

### Expected Behavior

Images

### Observed Behavior

<class 'dcim.models.devices.DeviceRole.DoesNotExist'>

DeviceRole matching query does not exist.

Python version: 3.9.2
NetBox version: 3.6.6
Plugins: 
  netbox_topology_views: 3.8.1

**Comment by fbaschin** [comment]
I fixed it like this
https://github.com/netbox-community/netbox/discussions/13224

**Comment by dreng** [comment]
Unfortunately, we cannot prevent orphaned database entries from occurring. To do this, NetBox itself would have to be changed, but this is not possible as NetBox cannot know anything about the structure of plugins.

What we could possibly do is to catch this error and display a dummy icon or automatically delete the database entry.

**Comment by dreng** [comment]
I wasn't able to reproduce this issue. If I remove a device role, it won't be shown anymore. Therefore it is not possible to click on a corresponding image. Unfortunately you did not provide the steps to reproduce.

I set this to "pending closure" and close it in a few weeks if the needed steps to repoduce haven't been provided.
