### ISSUE TITLE
Make the curvature of cables and connections adjustable

### ISSUE THREAD

**Issue by hacklschorssh** [mattieserver/netbox-topology-views#436]
### NetBox version

3.6.6

### Topology Views version

3.1.0

### Feature type

Change to existing functionality

### Proposed functionality

Please make this feature adjustable, or turn it off completely. 

### Use case

When building projects with more than a few nodes it quickly becomes apparent, that the cables and connections curve towards the middle. This is a nice tool to find the middle of the workspace, but the farther you get from the middle the bigger the curve gets. And with less than 100 nodes it already looks weird on the more distant clusters. 
It's a small issue but making it adjustable makes the whole topology much more presentable.

**Comment by dreng** [comment]
Hi,

please be so kind and provide a screenshot of what looks weird to you.

As we use an engine (vis.network), I'm not sure if this is adjustable in general, but we can check this.

**Comment by hacklschorssh** [comment]
Sure, these nodes are a good example: 

![topologydetail](https://github.com/mattieserver/netbox-topology-views/assets/155171757/a265765c-0c03-4d19-80ed-646357962194)

**Comment by glivolsi** [comment]
You can try to set physics or smooth to false 

https://visjs.github.io/vis-network/docs/network/edges.html

**Comment by evl-gg** [comment]
I second this. We are documenting a larger environment and the curvature of the lines, especially on objects closer together is a serious problem. Can this be added as an option to straighten all lines?

**Comment by xtxerr** [comment]
netbox_topology_views/views.py
263d262
<     edge["smooth"] = {'type': 'continuous', 'roundness': 1}

**Comment by dreng** [comment]
> edge["smooth"] = {'type': 'continuous', 'roundness': 1}

Not an ideal option in my opinion. It seems obvious that the best preference is a very individual thing. Therefore we should make this an individual option.

You may have a look at https://jsbin.com/fobugitota/edit?html,js,output and tinker around a bit. Smooth type "dynamic" is the only one that renders many cables side by side instead of rendering them all at the same position. The value to adjust seems to be "length" instead of roundness and smooth type.

**Comment by xtxerr** [comment]
> > edge["smooth"] = {'type': 'continuous', 'roundness': 1}
> 
> Not an ideal option in my opinion. It seems obvious that the best preference is a very individual thing. Therefore we should make this an individual option.
> 
> You may have a look at https://jsbin.com/fobugitota/edit?html,js,output and tinker around a bit. Smooth type "dynamic" is the only one that renders many cables side by side instead of rendering them all at the same position. The value to adjust seems to be "length" instead of roundness and smooth type.

It should be configurable on an edge and node base, like this (but with configuration in SQL):

```
# individual edge styles between specific nodes can be set in "styles[]"
    styles = [
        # cable style between two specific nodes by node name
        {"nodeA": "router-foobar", "nodeB": "router-foobar-2", "type": "vertical", "roundness": 1, "forceDirection": False},
        # circuit style by circuit name
        {"nodeA": "dwdm-2", "fontalign": "right", "type": "horizontal", "roundness": 1, "forceDirection": False},
    ]
    for style in styles:
       if style['nodeA'] in [termination_a["termination_device_name"],termination_b["termination_device_name"]]:
          if 'nodeB' in style: 
             if style['nodeB'] in [termination_a["termination_device_name"],termination_b["termination_device_name"]]:
                edge["smooth"] = {
                   'type': style['type'],
                   'roundness': style['roundness'],
                   'forceDirection': style['forceDirection']
                }
          else:
              edge["smooth"] = {
                 'type': style['type'],
                 'roundness': style['roundness'],
                 'forceDirection': style['forceDirection']
              }
```
