### ISSUE TITLE
End to end relationship

### ISSUE THREAD

**Issue by joaolucasmacedo** [mattieserver/netbox-topology-views#45]
It would be nice to show in the topology only interfaces end to end relationship, as on the deprecated built-in feature. 
This way, we don't need to bring patch panels and other intermediary/passive  gear to the topology. 
Some times I need to tag 2 or 3 devices to reach the far end device in witch I need it to show up.
Look at the picture below. I just need the black phone to show directly connected to the switch.
![Topo](https://user-images.githubusercontent.com/66760118/92432643-2a35f880-f171-11ea-8db5-77760c190b03.png)

**Comment by pycolas** [comment]
Hello, I started working on that feature in this fork https://github.com/pycolas/netbox-topology-views/tree/end-to-end-connections

The goal is to display end-to-end connections between devices, and provide an option where the user can choose if he wants to hide some intermediate passive devices, like patch-panels, TAP, etc

**Example**

Without any filtering :
![with patch-panels](https://user-images.githubusercontent.com/104468038/166289208-3b9c80da-c1b9-4fe4-b5e7-dd665256c4cb.png)

Same view but with patch-panels filtering :
![without patch-panels](https://user-images.githubusercontent.com/104468038/166289329-109582ee-5a5c-4be3-862d-fcd2cff0e2b0.png)

And now with patch-panels and TAP filtering :
![without patch-panels and taps](https://user-images.githubusercontent.com/104468038/166289384-79d8cd64-7470-41e8-82e5-1b1f4b3045ae.png)

**Comment by joaolucasmacedo** [comment]
Maybe, rather than choosing which role to ride, it would be better just e checkbox to hide only front/rear port connections, as some devices may have interfaces and rear/front ports and they will be hidden.

**Comment by pycolas** [comment]
Do you have an example in mind ?

**Comment by joaolucasmacedo** [comment]
> 

Well, I cant say any example right now, but it makes more sense to deal with front/rear ports inside devices rather than selecting role to hide. Because if I need to hide some role,  I just wont select it.
Think about some device showing up in a topology that have connected interfaces and also some front/rear port, like a UPS with power surge protection for ethernet ports. Then, if I hide the role UPS it will not be shown.

**Comment by joaolucasmacedo** [comment]
Looks like it works just fine, as you showed. But I could not understand the logic on hiding some roles for that purpose, becase I would only not select them.
I can think about a logic where it checks intermediate devices on a end-to-end connection and shows them, or not, as a appropriate checkbox is checked or not.

**Comment by pycolas** [comment]
In my use case I have to filter the devices using roles AND tags, to create some "functional" views.
But a device can only have 3 tags, so I can't manage passive devices like you said, and add them or not in the form (some patch-panels would have a lot of tags, not possible).

Anyway, to accommodate with those two use cases, I am trying this :
- Add a checkbox to activate "end-to-end connections mode"
- Replace the field "hide role" with a new one where user can specify which kind of passive devices he wants to see on the diagram, when in end-to-end connection mode : in your use case this field would remain empty, but in mine I would be able to choose "TAP" (without requesting all of them in the query form).

I think it's make more sense now.

**Comment by mattieserver** [comment]
Hi,

Please submit a PR once you are ready.

Also it should have the option to be disabled as it is not needed in certain use cases.

**Comment by mattieserver** [comment]
this was added
