### ISSUE TITLE
Use GPS position for coordinates on a world map view

### ISSUE THREAD

**Issue by qlr-one** [mattieserver/netbox-topology-views#450]
### NetBox version

v3.6.6

### Topology Views version

v3.8.1

### Feature type

New functionality

### Proposed functionality

We would like for topology views to use a device's gps coordinates or if they are blank the Site's gps coordinates for that device as the coordiante setting for the device. Similar to the functionality in the librenms world view feature https://docs.librenms.org/Extensions/World-Map/. I believe this is similar to request https://github.com/mattieserver/netbox-topology-views/issues/425. Understanding that the custom image does not work due to zooming the use of the gps coordinated would allow for zoom to work in relation to the world map. 

### Use case

Currently we have to manually adjust drawing created by topology views and the use of gps for view coordinates would allow for more automated and logical organization of devices on the topology views.

**Comment by dreng** [comment]
Please see discussion #388
