### ISSUE TITLE
Add Interface/Port Label on Link

### ISSUE THREAD

**Issue by glivolsi** [mattieserver/netbox-topology-views#452]
### NetBox version

v3.7.1

### Topology Views version

v3.2.1

### Feature type

New functionality

### Proposed functionality

It would be very useful if in the topology view it would also be possible to add labels of interfaces and ports and possibly information regarding LACP, I do not thinkit is necessary to include information regarding IP addresses since it is a topology view and therefore not at L3 but if it does not involve very heavy queries even this information could be useful.

### Use case

Topology View with phisical & aggregate Link Information

**Comment by dreng** [comment]
Hi glivolsi,

this has been proposed and discussed a few times before. See #300, #126 and #71 for the reasons why the proposal will not be implemented.
