### ISSUE TITLE
VLAN map

### ISSUE THREAD

**Issue by leijonatm** [mattieserver/netbox-topology-views#456]
### NetBox version

v3.6.6

### Topology Views version

v3.7.0

### Feature type

New functionality

### Proposed functionality

It would be nice to have a visual way of showing vlan traffic between nodes and if possible search by vlan to see from which path it flows

### Use case

It would be a quick visual way to understand the logical network topology

**Comment by SimonFischer04** [comment]
Please use search once before opening issue. F.e: https://github.com/mattieserver/netbox-topology-views/issues/71
