### ISSUE TITLE
Add possibility for "Custom Fields" under Topology Views > Topology

### ISSUE THREAD

**Issue by torbensp** [mattieserver/netbox-topology-views#457]
### NetBox version

v3.7.1

### Topology Views version

v3.9.0

### Feature type

New functionality

### Proposed functionality

It would be very useful if custom fields could be assigned to appear under the "Topology" filter in "Topology View". At the moment it is only possible to assign custom fields under the following:

![image](https://github.com/mattieserver/netbox-topology-views/assets/43603621/2b073659-e55b-4f69-ae61-5c038d4a35c5)

- Topology Views > Circuit Coordinate
- Topology Views > Coordinate
- Topology Views > Coordinate Group
- Topology Views > Individual Options
- Topology Views > Power Feed Coordinate
- Topology Views > Power Panel Coordinate
- 
Please note that It is possible to add a custom field to "Topology" by assigning it DCIM > Device but then it would also appear as a custom field in many other menus, which may not be desired.

### Use case

In order to make it possible to have a more specific representation of a topology view. This could be useful if only a specific system should be shown or if only certain type of cables should be shown, like fiber or LAN cables.

**Comment by mattieserver** [comment]
Unfortunately, i dont see this as possible.
The current options you have are because we had to create an extra model in netbox.
The "Topology" itself is not a model and i dont see how it would ever be a model.
