### ISSUE TITLE
Pull 462 causes export xml to fail and crashes if circuits are added while showing terminations

### ISSUE THREAD

**Issue by ManifestFailure** [mattieserver/netbox-topology-views#463]
### NetBox version

v3.7.2

### Topology Views version

github develop

### Steps to Reproduce

 Install the development version of topology views to the netbox venv then run `python3 manage.py migrate netbox_topology_views` and `python3 manage.py collectstatic --no-input`

**Download XML issue**

Attempt to Download XML on any topology regardless of if any nodes are present

**Circuit issue**

1. Create an `Organization -> Sites` with any details.
2. Create a dummy Device for the site with at least 1 interface.
3. Create a `Circuits -> Providers` entering only a Name and the Slug.
4. Create a `Circuits -> Circuit Type` entering only a Name and the Slug.
5. Create a `Circuits -> Circuits` selecting the Provider and Circuit Type created above. Set the Circuit ID to any number.
6. In the Circuit, set Termination A to the Site, then connect it to the Interface for the Device. Termination Z can be left empty.
7. Attempt to filter the Topology to the site, selecting `Show Circuit Terminations`.

### Expected Behavior

Be able to download the XML topology and view the topology when `Show Circuit Terminations` is selected

### Observed Behavior

When trying to download the XML Topology, it downloads topology.xml that contains the html code for the server error.

![image](https://github.com/mattieserver/netbox-topology-views/assets/106504708/b4665935-8c0e-40b1-9e6f-9b0dbbdf5db9)

When attempting to filter Topology with `Show Circuit Terminations`, the site goes to the below server error page.

![image](https://github.com/mattieserver/netbox-topology-views/assets/106504708/5756c0ab-5f62-4353-b22e-0025b6eb2a19)

**Comment by dreng** [comment]
Fixed in #466 . Thanks for reporting!
