### ISSUE TITLE
Circuit Termination Index Error | Topology Tags not searchable | Co-ordinates only mostly persistent

### ISSUE THREAD

**Issue by dyemi6075** [mattieserver/netbox-topology-views#467]
### NetBox version

3.7.1

### Topology Views version

3.9.0

### Steps to Reproduce

Topology Filter select "Show Circuit Terminations"
Press search
Provides the following error:

<class 'IndexError'>

list index out of range

Python version: 3.11.5
NetBox version: 3.7.1
Plugins:
netbox_circuitmaintenance: 0.3.0
netbox_documents: 0.6.3
netbox_topology_views: 3.9.0
netbox_webhook_receiver: 0.2.0

Searchable tags not available in Topology Search

Open Topology Filter
Select Tags search box. No Tags are listed
Bug/Request (not sure)
Colour of circuits/logical connections can be changed if in Planned, decom ect states

Expected Behavior
Show Circuit Terminations:

Able to show circuit terminations on topology (This works with show logical connections)

Tags:

Expect to be able to draw a topology based on tags appended to circuits or devices

Logical Connections/Circuits in Active, Planned or Decommissioned state have different colours on Topology

Observed Behavior
show circuit terminations:

<class 'IndexError'>

list index out of range

Python version: 3.11.5
NetBox version: 3.7.1
Plugins:
netbox_circuitmaintenance: 0.3.0
netbox_documents: 0.6.3
netbox_topology_views: 3.9.0
netbox_webhook_receiver: 0.2.0

Tags:

No Tags found to be selected in Filter

No colour changes available for different state logical connections or circuits.

I can see circuit types can be given different colours, but that requires the circuit termination option to work I expect

Co-ordinate saving

Most of the items seem to be saved in their co-ordinates. But there happens to be a couple of objects that never retain their co-ordinates.

Co-ordinate saving has been turned on in conifig BTW.

### Expected Behavior

Topology Filter select "Show Circuit Terminations"

Searchable tags not available in Topology Search

Open Topology Filter
Select Tags search box. No Tags are listed
Bug/Request (not sure)
Colour of circuits/logical connections can be changed if in Planned, decom ect states

Expected Behavior
Show Circuit Terminations:

Able to show circuit terminations on topology (This works with show logical connections)

Tags:

Expect to be able to draw a topology based on tags appended to circuits or devices

Logical Connections/Circuits in Active, Planned or Decommissioned state have different colours on Topology

No Tags found to be selected in Filter

No colour changes available for different state logical connections or circuits.

I can see circuit types can be given different colours, but that requires the circuit termination option to work I expect

Co-ordinate saving

Most of the items seem to be saved in their co-ordinates. But there happens to be a couple of objects that never retain their co-ordinates.

Co-ordinate saving has been turned on in conifig BTW.

Expect for a saved filter and co-ordinates to be saved.

Can we add custpm co-ordinates

### Observed Behavior

Topology Filter select "Show Circuit Terminations"
Observed error:

<class 'IndexError'>

list index out of range

Python version: 3.11.5
NetBox version: 3.7.1
Plugins:
netbox_circuitmaintenance: 0.3.0
netbox_documents: 0.6.3
netbox_topology_views: 3.9.0
netbox_webhook_receiver: 0.2.0

Tags
Searchable tags not available in Topology Search. Empty drop down box

Co-ordinate saving

Co-ordinates can be saved on per filter basis

**Comment by dreng** [comment]
Hi, thanks for your bug report. Unfortunately it is confusing and messy. Please review it and tidy up.

**Comment by jrsalla** [comment]
> Hi, thanks for your bug report. Unfortunately it is confusing and messy. Please review it and tidy up.

I'm having problems with the created tags, which don't show up in the filters. Another behavior I noticed is when I save searches with the "show cables" flag, the field is not checked when I use the saved search.

![image](https://github.com/netbox-community/netbox-topology-views/assets/26460873/f56a5542-4194-429b-9778-9ecb76fc9d69)

**Comment by dreng** [comment]
1. Please do not mix up different issues. Create a bug report for each issue instead.
2. Use the bug report template properly.
3. Put as much effort as possible into a bug report. It is not the job of the developers to sort out important parts in order to guess what the problem is.

Unfortunatly you didn't react on my first answer. I suppose there's no problem anymore then. Feel free to create new bugs respecting the things mentioned above.
