### ISSUE TITLE
Prepare for NetBox v4.0

### ISSUE THREAD

**Issue by dreng** [mattieserver/netbox-topology-views#477]
### NetBox version

v3.7.4

### Topology Views version

v3.9.0

### Feature type

Change to existing functionality

### Proposed functionality

NetBox 4.0 beta has been released and we should be prepared when the final version is out.

See migration notes at https://netboxlabs.com/docs/netbox/en/stable/plugins/development/migration-v4/

Current check list:
- Make sure that Python version is > v3.9 (check CI/CD also)
- ~~Change extras.plugins to netbox.plugins~~ **Done. See** #487
- Convert ContentType to ObjectType
- ~~Convert View actions to dictionaries~~ **Does not apply**
- ~~Remove BootstrapMixin~~ **Does not apply**
- ~~Update Fieldset Definitions~~ **Done. See** https://github.com/netbox-community/netbox-topology-views/pull/495/commits/a56bc1e52f0fcbba0f64d5ab3dd5c57a46e41f4a
- ~~Remove button colors~~ **Done. See** #491 
- ~~Rename template blocks~~ **Done. See** https://github.com/netbox-community/netbox-topology-views/pull/495/commits/a56bc1e52f0fcbba0f64d5ab3dd5c57a46e41f4a
- Utilize flex controls
- ~~Check column offsets~~ **Does not apply**
- Tables inside cards
- Remove nested tables inside cards
- Remove btn-sm class from buttons
- Update bg-$color classes
- Check for removed obsolete custom CSS classes
- Extend API serializer for brief mode
- ~~GraphQL~~ **Does not apply**

**Comment by dreng** [comment]
Started an extra branch (https://github.com/netbox-community/netbox-topology-views/compare/develop...477_prepare_for_netbox_4.0).

Please update the original thread if you complete a task.

**Comment by brandan-schmitz** [comment]
Just wondering if there is a ETA on finishing this now that Netbox 4.0.0 and 4.0.1 have been released?

**Comment by dreng** [comment]
> Just wondering if there is a ETA on finishing this now that Netbox 4.0.0 and 4.0.1 have been released?

No, there isn't. It's done when it's done. Of course, everybody is welcome to contribute in order to push a faster release. ;-)

**Comment by mattieserver** [comment]
I ran into some issues, will try have it ready after the weekend.

**Comment by AndreKotze** [comment]
Good day all,

I'm trying to install the plugin on a fresh install of Netbox 4.0.2 however I get the below errors when I run the "python3 manage.py migrate netbox_topology_views" command.  Am I doing something wrong or is the plugin not working on v4 yet?

Thanks in advance,

Traceback (most recent call last):

_[Deleted Traceback, because it is not helpful at all in this state and it clutters the thread -- dreng --]_

**Comment by mlazzarotto** [comment]
> Good day all,
> 
> I'm trying to install the plugin on a fresh install of Netbox 4.0.2 however I get the below errors when I run the "python3 manage.py migrate netbox_topology_views" command. Am I doing something wrong or is the plugin not working on v4 yet?
> 
> Thanks in advance,

The plugin is not ready for Netbox 4, yet.

**Comment by AndreKotze** [comment]
> The plugin is not ready for Netbox 4, yet.

Thank you for the confirmation.

**Comment by retrogamer999** [comment]
do we have an eta of when the plugin will be ready for 4.0.0? just need to set some expectations to the powers that be.

**Comment by dreng** [comment]
Hi all,

I completely understand why you are asking impatiently, but everything there is to say about this is already written in the first post above. There are all the points that still need to be done and where to find the 4.0 branch.

There is no ETA because we are not rushing. This has been answered already. I myself would also like to have the upgrade ready and upgrade my NetBox version to 4.0. However, there are a few issues why it is taking so long this time:

1. We are a very small team of only two people.
2. I am currently working a lot and have little free time (I think the same applies to Mattijs).
3. The weather is great and there's little reason to sit in a stuffy room in front of a screen instead of enjoying the nature outside.

If you need it to be done faster, contribute to the project. Any help is very welcome.

**Comment by natm** [comment]
https://linear.app/netboxlabs/issue/ENG-2990/

**Comment by mlazzarotto** [comment]
Good morning, I noticed that there is version **4.0.0b1** on PyPI in **pre-release**, and therefore I was wondering if you already know when this version will become stable for use with Netbox.
Thanks again for the work you put into this project 🙂
