### ISSUE TITLE
Add Ignore Termination Types to "regular" filters

### ISSUE THREAD

**Issue by julian-martinz** [mattieserver/netbox-topology-views#485]
### NetBox version

v3.7.6

### Topology Views version

v3.9.1

### Feature type

New functionality

### Proposed functionality

Move / add the `Ignore Termination Types` filter, which is currently found under the global individual options, to the regular filter options within the topology view.

### Use case

We started modelling our power in netbox. To have a clean picture of the power topology any non-power connections need to be ignored. Afaik this is only possible by using  the `Ignore termination types` filter.  
While this generally works fine, you need to switch this (global) setting whenever you want to display 'power' or 'network' topologies. Once the filter would've been added to the regular filter page, different topology types (power / network) could be easily bookmarked / reproduced for anyone

**Comment by dreng** [comment]
Sounds reasonable.
