### ISSUE TITLE
See only blank page with filters and without filters

### ISSUE THREAD

**Issue by MalteKiefer** [mattieserver/netbox-topology-views#486]
### NetBox version

v376

### Topology Views version

v391

### Steps to Reproduce

I set these filters

![Bildschirmfoto vom 2024-04-29 15-27-34](https://github.com/netbox-community/netbox-topology-views/assets/59220985/186565ac-0ae9-45c2-b741-a0210437ca21)

### Expected Behavior

I want to see my topology.

### Observed Behavior

Blank page
![image](https://github.com/netbox-community/netbox-topology-views/assets/59220985/00462b0b-ce8b-47ff-b7d4-4dce8df4a917)

**Comment by mattieserver** [comment]
Can you see if the browser console shows any logs?

**Comment by MalteKiefer** [comment]
![image](https://github.com/netbox-community/netbox-topology-views/assets/59220985/ced105dd-b12f-4d51-ad49-af2659ee8f79)

**Comment by MalteKiefer** [comment]
Don't think has something to do with it.

**Comment by mattieserver** [comment]
Did you actually press search on the topology page?

**Comment by MalteKiefer** [comment]
Sorry my mistake.
![image](https://github.com/netbox-community/netbox-topology-views/assets/59220985/16c713ab-25bf-4b8d-b902-80483c68f31b)
