### ISSUE TITLE
Virtualization Support

### ISSUE THREAD

**Issue by seeder** [mattieserver/netbox-topology-views#499]
### NetBox version

v3.7.6

### Topology Views version

v3.9.1

### Feature type

New functionality

### Proposed functionality

Add ability to visualize Virtualization Clusters and VMs as part of the topology diagram.

### Use case

Enables more comprehensive visualization. Especially for viewing network structure, where some routers and firewalls are virtual machines.

**Comment by mattieserver** [comment]
This has been suggested a few times but we currently don't plan on adding it because there is no clean way to add it.

**Comment by seeder** [comment]
A quick look through the code suggest just replicating what you are doing with imports from `dcim.models` and using `virtualization.models`

**Comment by dreng** [comment]
1. The word "just" simply does not fit here.
2. Virtual interfaces can't connect to each other in NetBox. There is no virtual cables model. The network structure you are talking about is not modeled in NetBox yet. No data, no visualisation. So the best result we can get is showing a bunch of icons without connections. This is not what I call a topology. There is simply no benefit but a LOT of work if you take every aspect into account.

**Comment by seeder** [comment]
I am sorry if the word "just" offended you, that was not my intension.

But when I use my imagination, I can see  Virtualization Cluster have  assigned Devices  ( vm hosts ) and VMs, which already creates the ability draw out the a relationship there.  

While VM interfaces and not perfectly integrated, they have tunnel type, which can also be used to draw up relations with other entities in the inventory.

When it comes to the use of this plugin, it has a wide range of applicability when it comes to what the visuals are for, and believe me, it will make a lot of people happy having only icons inside boxes. I am one of them :)

**Comment by dreng** [comment]
> I am sorry if the word "just" offended you, that was not my intension.

Don't worry. It didn't. I only wanted to make clear that it's by far not as quickly done as one may think.
