### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by JamesKBowler** [mattieserver/netbox-topology-views#50]
Hello,

I have installed the latest version via pip for both Netbox and this plugin

Netbox: 2.10.3
Netbox Topology Views: 0.4.10
Python: 3.8.5

The only item I added to the configuration.py file is this..

```
PLUGINS = [
    "netbox_topology_views"
]
```

I've tried adding the `PLUGINS_CONFIG` example on the ReadMe but I get the same 404 error.

These errors show up when I browse to the plugin page.

`http://my-server:8000/plugins/topology-views/`

```
[20/Jan/2021 07:19:02] "GET /api/plugins/topology-views/preselectdeviceroles/ HTTP/1.1" 404 40993
[20/Jan/2021 07:19:02] "GET /api/plugins/topology-views/preselecttags/ HTTP/1.1" 404 40993
```

and using the search function I get this.
![image](https://user-images.githubusercontent.com/24221328/105141102-89792180-5af0-11eb-94c2-bf17e380020b.png)

Any ideas?

Thanks

**Comment by tim427** [comment]
Hey @JamesKBowler what version van NetBox are you using?

**Comment by JamesKBowler** [comment]
Hi @tim427 I have updated the request.

Cheers

**Comment by tim427** [comment]
@JamesKBowler I think you meant the NetBox Topology Views version 0.4.10 ;)
So what version of NetBox itself are you using ;) ?

**Comment by JamesKBowler** [comment]
@tim427 updated thanks :)

**Comment by mattieserver** [comment]
Hi,

Netbox change something in v2.10.0 and I can lo longer get the API calls to work.
The documentation does not provide any meaningful info so I am looking into what can be done.

But for the time being, the plugin will not work on the latest version of netbox.

**Comment by JamesKBowler** [comment]
Thanks for coming back to me. Which version of Netbox do you suggest?

**Comment by tim427** [comment]
v2.9.11 is the latest/newest before v2.10.x. Breaking changes were introduced in v2.10

**Comment by JamesKBowler** [comment]
Thanks, closing off.
