### ISSUE TITLE
UX changes

### ISSUE THREAD

**Issue by cpmills1975** [mattieserver/netbox-topology-views#500]
### NetBox version

3.7.8

### Topology Views version

3.9.1

### Feature type

Change to existing functionality

### Proposed functionality

Apologies if any of this has been suggested already, I've only been playing with this plugin for a couple of days.

I'd like to suggest the following UX changes: There's potentially a few separate FRs here.

1) That the plugin moves away from using saved filters as it currently does and moves towards defining a topology view as a first class model. Saved filters are extremely difficult to edit after they are initially created - adding objects to them requires editing the JSON. Saving the options including show cables etc makes little sense in a saved filter.

2) The topology view would collect together the objects to be included in that view, as the saved filter does now, and the options to be applied to that view - view cables, etc. It could also be the coordinate group. Perhaps the coordinate group is the model I'm looking for, but needs renaming and extending?

3) The menu option for topology views would leverage the NetBox table functionality to list topology views visible to the users. Users will be able to open and view any topology view without effectively having to re-create it from a coordinate group and saved filter as currently.

4) The topology view would permit tags, tenancy, etc to be applied such that the full functionality of the NetBox permissions model can be applied to it. Perhaps relevant topology views (i.e those that contain relevant objects) should be listed from sites, locations, device lists, etc across the NetBox UI. Can NetBox plugins register dropdown lists at the top right of the detail pages?

5) The ability to select the types of ports to render cables/links for - a topology view showing power connectivity should show power ports and outlets, while a console port topology view would show console ports and console server ports and a networking diagram would show interfaces. Any of the above could include front/rear ports as these are effectively agnostic. This setting would be an attribute of the topology view.

### Use case

The current functionality is useful, but not immediately intuitive to users.

### External dependencies

None.

**Comment by k109x** [comment]
It would be nice to add an option to display port\interface ID's directly on the topology (on the link) rather than on a tooltip.

![Screenshot 2024-06-24 103503](https://github.com/netbox-community/netbox-topology-views/assets/52101050/74901b37-6d9d-49a5-a5d0-7a068cd3ed7f)

**Comment by dreng** [comment]
Please do not mix up different proposals. Each proposal has to be in a separate issue. By the way, no. 1 is a NetBox issue and not changeable by us.

@k109x Also, please do not hijack issues. You proposal has been asked for many times. This won't be implemented for a couple of reasons.

**Comment by cpmills1975** [comment]
I disagree that number 1 is a NetBox issue. Plug-ins are able to define custom models and my proposal was to use that rather than saved filters to store the list of objects to be displayed.

Sadly this makes this plugin unsupportable for non-engineering folk and therefore I cannot recommend it in its current form to my users.

**Comment by mattieserver** [comment]
The issue i have with number 1 is that we would need to recreate a whole lot of relations between the other models.
This would also cause a lot of duplicate code. I tried to move some of the filters to a new model but i did not really like it. (code wise).

The plugin also was (and is) created to draw a topology ad-hoc, saved filters somewhat provided a way to have persistent views.
