### ISSUE TITLE
NetBox 4.x

### ISSUE THREAD

**Issue by alfista-sk** [mattieserver/netbox-topology-views#512]
### NetBox version

v4.x

### Topology Views version

v3.x

### Feature type

New functionality

### Proposed functionality

Hi, is possible to update it, that this plugin can be installed and is supporting the latest NetBox version 4.x?

### Use case

We installing the latest NetBox and will use your plugin in it.

### External dependencies

Thanks.

**Comment by mattieserver** [comment]
Use the beta releases for now.
