### ISSUE TITLE
Setting Plugin Configurations causes 502 Error

### ISSUE THREAD

**Issue by sachenbachtherma** [mattieserver/netbox-topology-views#514]
### NetBox version

v4.0.3

### Topology Views version

v4.0.0

### Steps to Reproduce

Copy/Paste plugin configuration in configuration.py from README, confirmed it was exact syntax required.
Restart netbox and netbox-rq services.

### Expected Behavior

Netbox to function properly

### Observed Behavior

Receive a 502 error after refreshing netbox.

Commenting out the configuration lines and restarting the services corrects the issue.

**Comment by mattieserver** [comment]
Please provide more information, it works and was tested with all options set.

**Comment by sachenbachtherma** [comment]
Ugh, please disregard.  I'm glad you asked for additional info, as I was digging through the service logs it said there was an indentation error in the plugin config, turns out there was a space that didn't belong.  Thank you for your hard work getting this up to 4.0!

**Comment by sachenbachtherma** [comment]
Space in front of "PLUGINS_CONFIG" caused the error, not due to the plugin.
