### ISSUE TITLE
Filter by Prefix

### ISSUE THREAD

**Issue by felix-sterzelmaier-concat** [mattieserver/netbox-topology-views#517]
### NetBox version

4.0.6

### Topology Views version

4.0.0

### Feature type

New functionality

### Proposed functionality

Add a new filter to allow filtering by Prefix

### Use case

This allows to show all elements in a prefix.

### External dependencies

none

**Comment by dreng** [comment]
I'm afraid, this is not doable. The filter mechanism filters devices and NetBox does not filter devices by IPAM information. Correct me if I'm wrong.

**Comment by mattieserver** [comment]
Yes, we would have to add our own logic to apply this filter and I currently don't plan to add this.

Feel free to create a PR if you really want this.

**Comment by dreng** [comment]
I think, the only good approach would be to add a feature request upstream (add ability to filter devices by IPAM information). Personally, I'm not a fan of working against NetBox' logic.
