### ISSUE TITLE
The complete exception is provided below:

### ISSUE THREAD

**Issue by SerhiiZahuba** [mattieserver/netbox-topology-views#524]
### NetBox version

4.0.

### Topology Views version

4.0.0

### Steps to Reproduce

1) Set filters
2) Click Search

### Expected Behavior

Result

### Observed Behavior

Error 500

![image](https://github.com/netbox-community/netbox-topology-views/assets/36307887/4d90e415-4ae2-4ef2-b9c4-d53d36430cfe)
![image](https://github.com/netbox-community/netbox-topology-views/assets/36307887/9cda1919-b019-4545-99d6-e3971d44a4e4)

**Comment by mattieserver** [comment]
Unfortunately i do not have enough info to help you.

Please provide all the filters you used (the URL is fine, without the domain).

Also try with different filters to try and see if you can find if the issue is linked to a specify device.

**Comment by SerhiiZahuba** [comment]
I've tried different options for devices\filters but I keep getting the error.
Maybe i can get a debug of this somewhere?

**Comment by dreng** [comment]
> I've tried different options for devices\filters but I keep getting the error. Maybe i can get a debug of this somewhere?

If you need help you should follow the advise:

> Please provide all the filters you used (the URL is fine, without the domain).
