### ISSUE TITLE
Exclude coordinates from main search results

### ISSUE THREAD

**Issue by Azmodeszer** [mattieserver/netbox-topology-views#533]
### NetBox version

4.0.7

### Topology Views version

4.0.0

### Feature type

Change to existing functionality

### Proposed functionality

This may be asking too much for too little actual benefit, but let's see.

When coordinate saving is enabled, discrete database objects are created under Device Coordinates. These are linked to their respective device by its name. A side effect of this is that when you look up a device through the main search, even if the name is an exact match, there are **_always_** at least two results, i.e. you're directed to a results page showing the coordinate pair and the device itself instead of going straight to the device page.

So what, big deal, you might say, one more click, but I dunno... I do a lot of work and searching in our NB instance on a daily basis and it kind of adds up? Especially considering that the coordinate objects aren't really relevant as a result anyway and it might even be a tad confusing to someone not familiar with the plugin?

If I want to view or delete coordinate assignments, I can do this just as well by going directly to Device Coordinates and filtering by device name. For 99.99% of cases there is no reason that I can see to have this object show up in the results and all it does is add time and navigation effort.

### Use case

Improve clarity and save time and effort.

**Comment by Azmodeszer** [comment]
Yup, I'm an idiot. I could've sworn the search drops you directly at the page if there is only one result, but evidently that's not true. There's a results page either way...

Welp, disregard. Sorry.

**Comment by mattieserver** [comment]
Its true that the coordinates are visible in the search (added in netbox_topology_views/search.py).
I agree that it might not be all that useful. 
But if you know you are looking for a device you might use the search function from the devices page instead of the global search, that way you avoid any other results showing up and it might be a little bit faster, i understand that is also less elegant to use.

**Comment by dreng** [comment]
@Azmodeszer @mattieserver 
While this has been closed already, personally I have no problem with changing the behavior. If I am not completely wrong, it is sufficient to delete search.py, where these searches have been defined. I would be interested in your opinion.

> For 99.99% of cases there is no reason that I can see to have this object show up in the results and all it does is add time and navigation effort.

I completely agree.

**Comment by Azmodeszer** [comment]
Glad to see my issue wasn't completely pointless after all. Yeah, I don't really see any utility in having the coordinates show up in the search.

**Comment by dreng** [comment]
Hmm, just tested the idea of removing the search.py. Unfortunately this leads to an error: 'NoneType' object has no attribute 'display_attrs'

I don't know why this error occurs, not why the search.py should be mandatory. The docs suggest, it's optional: https://netboxlabs.com/docs/netbox/en/stable/development/search/
