### ISSUE TITLE
Cables not Showing withe diffrent Language Setting

### ISSUE THREAD

**Issue by FinnEngenhorst** [mattieserver/netbox-topology-views#543]
### NetBox version

v4.0.8

### Topology Views version

v4.0.0

### Steps to Reproduce

1. Create some sort of Topology View withe Cables showing
2. Change Language to German or Other  
3. Reload before created Topology View

### Expected Behavior

Show Cables withe diffrent Language setting than Englisch

### Observed Behavior

Cables not showing withe diffrent Language setting than Englisch
Testet withe German an Spanish

**Comment by dreng** [comment]
Hi Finn,

Thanks for your bug report. This has been reported in #464 already and has been fixed in #541. The fix will be included in the next release.
