### ISSUE TITLE
DeviceType object has no attribute get_full_name with NetBox 4.1

### ISSUE THREAD

**Issue by ibuclaw** [mattieserver/netbox-topology-views#564]
### NetBox version

v4.1.0

### Topology Views version

v4.0.1

### Steps to Reproduce

1. Open to Organization > Sites > Pick a site
2. Click Topology button

### Expected Behavior

Topology view of site to open on page.

### Observed Behavior

A 500 server error is returned.

The complete exception is below:
```
<class 'AttributeError'>

'DeviceType' object has no attribute 'get_full_name'

Python version: 3.11.2
NetBox version: 4.1.0
Plugins:
  netbox_topology_views: 4.0.1
```

This looks to be introduced by a 4.1 breaking change https://github.com/netbox-community/netbox/commit/0b77b3372c067fe1fd8c0fc5ab40ca3732e31288

Renaming `get_full_name` to `full_name` in the topology views.py source fixes the issue.

**Comment by ibuclaw** [comment]
I have a fix in my local branch, though it might be wise to do more testing to see whether there's any more fallout from the netbox 4.1 release.

**Comment by mattieserver** [comment]
#565 was created to add support for v4.1.0
