### ISSUE TITLE
Netbox v4.1.0 support

### ISSUE THREAD

**Issue by mattieserver** [mattieserver/netbox-topology-views#565]
### NetBox version

v4.1.0

### Topology Views version

v4.1.0

### Feature type

Change to existing functionality

### Proposed functionality

Netbox v4.1.0 support

### Use case

Netbox v4.1.0 support

**Comment by dreng** [comment]
I played around with various options for a couple of hours and it seems that renaming get_full_name to full_name is sufficient. This is exactly what @ibuclaw suggested.

https://github.com/netbox-community/netbox-topology-views/blob/f8c6e9e193ebe2f9352632283a0790e46334bbfd/netbox_topology_views/views.py#L149
