### ISSUE TITLE
Provide API for Coordinates and Coordinate Groups

### ISSUE THREAD

**Issue by dreng** [mattieserver/netbox-topology-views#570]
### NetBox version

v4.1.1-dev

### Topology Views version

v4.1

### Feature type

Change to existing functionality

### Proposed functionality

Provide API functionality like requested here https://github.com/netbox-community/netbox-topology-views/discussions/569

### Use case

Coordinates and Coordinate Groups would be accessible via API.

**Comment by betadrome** [comment]
@dreng sorry, I have not been available. That's insane, thanks a lot for implementing this feature!
