### ISSUE TITLE
Filter by Location

### ISSUE THREAD

**Issue by darcynz** [mattieserver/netbox-topology-views#59]
2.11 enables locations to classify of sub locations of a site.

It would be great to be able to filter Locations like we do Regions as this will allow a user to easily show a building, floor, or room within a location.

**Comment by mattieserver** [comment]
This is now available in version v0.5.2.

**Comment by mattieserver** [comment]
Should be version v0.5.3. (I made a mistake in the build with the version)

**Comment by darcynz** [comment]
Have updated and it might have caused an issue as no devices are appearing in the topology map now. 

Also the locations filter does not seem to populate with any locations.

**Comment by mattieserver** [comment]
What version of netbox? v2.11.2?

**Comment by darcynz** [comment]
Correct latest version

**Comment by mattieserver** [comment]
Can you clear your browser cache? I will check agains that version, i was using the develop branch.

**Comment by darcynz** [comment]
Must have been browser cached, checked it again today and its working.

Like regions nested locations don't seem to appear. Would it be difficult to get that to work?

Other wise its awesome :)

**Comment by mattieserver** [comment]
For now nested locations will not work.
