### ISSUE TITLE
Problem with roles

### ISSUE THREAD

**Issue by EAleg** [mattieserver/netbox-topology-views#65]
Hi, how add own role or slugs in this plugin? 
Because, my devices dont have next names (roles, slugs) Router, Firewall and so on.

**Comment by mattieserver** [comment]
Do you wan to add the image or the preselected roles?

**Comment by EAleg** [comment]
> Do you wan to add the image or the preselected roles?

Hi Mat, thank you for answer!I want to add my own image and roles.

Example, my Switch has role A-PE. And i want that Switch has image - Red Ball (this is my image).

PLUGINS_CONFIG = {
'netbox_topology_views': {
'device_img': 'redball',
'preselected_device_roles': 'A-PE'
}
}

Is that right?

And please write what characteristics the images should have.
Thank you.

**Comment by mattieserver** [comment]
The image needs to be the same name as the role slug, so for the role A-PE this will probably  just be a-pe.  
So the config would then be:

PLUGINS_CONFIG = {
'netbox_topology_views': {
'device_img': 'a-pe',
'preselected_device_roles': 'a-pe'
}
}

In the static/netbox_topology_views/img/ folder the redball image needs to be renamed to a-pe.png.

**Comment by EAleg** [comment]
> The image needs to be the same name as the role slug, so for the role A-PE this will probably just be a-pe.
> So the config would then be:
> 
> PLUGINS_CONFIG = {
> 'netbox_topology_views': {
> 'device_img': 'a-pe',
> 'preselected_device_roles': 'a-pe'
> }
> }
> 
> In the static/netbox_topology_views/img/ folder the redball image needs to be renamed to a-pe.png.

Thank you for help!
