### ISSUE TITLE
Nginx returns 502 Bad Gateway

### ISSUE THREAD

**Issue by Narek307** [mattieserver/netbox-topology-views#68]
Nginx returns 502 Bad Gateway error after Plugin installation and activation. Netbox: v2.9.8, Netbox_topology_views: v0.4.10

**Comment by mattieserver** [comment]
Hi,

Can you run `python3 manage.py collectstatic --no-input` in your venv just to be sure all the files are copied?

**Comment by Narek307** [comment]
The problem solved. 
https://netbox.readthedocs.io/en/stable/plugins/
