### ISSUE TITLE
Floating topology

### ISSUE THREAD

**Issue by Narek307** [mattieserver/netbox-topology-views#69]
Is it possible to have topology with fixed position icons?

**Comment by mattieserver** [comment]
Yes, you need to follow the steps under "Custom field: coordinates" in the readme.

Then you need the add the "allow_coordinates_saving" option to the plugin options.( Set it to True)

**Comment by Narek307** [comment]
Thanks for the prompt response.
I did as mentioned in README. After that I have run 'python3 manage.py collectstatic --no-input' and restart the netbox but configs don't change anything.

PLUGINS = ["netbox_topology_views"]
PLUGINS_CONFIG = {'netbox_topology_views': {'allow_coordinates_saving': 'True',
    'enable_circuit_terminations': 'True'}}

**Comment by mattieserver** [comment]
Hi, 

Can you try with just True ( remove the ' from before and after True).

You might also have to restart netbox: ( systemctl restart netbox)

You should then see a new check box in the layout to save the coordinates.

**Comment by Narek307** [comment]
It works. Thank You, much appreciated.
