### ISSUE TITLE
NetBox v3.0 Support

### ISSUE THREAD

**Issue by ryanmerolle** [mattieserver/netbox-topology-views#72]
As an FYI here is what changed that could impact or help the plugin:
- HTML Template updates (support change from bootstrap 3 to bootstrap 5)
- Overall UI tweaks
- Custom Queue Support for Plugins netbox-community/netbox/issues/6651

If you find any issues or have any questions feel free to hit us on the slack or add a bug /issue or add to the umbrella UI issue netbox-community/netbox/issues/6797

**Comment by mattieserver** [comment]
Hi;

Thanks for the heads-up, i saw the announcement and plan to create a new version of the plugin.
I will also try to follow the netbox devs and use typescript so it might take some time before i get it working.

**Comment by ryanmerolle** [comment]
Yep this is just a courtesy issue from the NetBox maintainers to some of the more popular plugins.

**Comment by DonMusto** [comment]
Hi there, I just installed NetBox 3.0.1 and get the following error, is it related?

<class 'django.template.exceptions.TemplateDoesNotExist'>

base.html

Python version: 3.9.6
NetBox version: 3.0.1

**Comment by mattieserver** [comment]
> Hi there, I just installed NetBox 3.0.1 and get the following error, is it related?
> 
> <class 'django.template.exceptions.TemplateDoesNotExist'>
> 
> base.html
> 
> Python version: 3.9.6
> NetBox version: 3.0.1

Yes, the plugin has not been updated to support the 3.0 release of netbox.
For now it would be best to uninstall the plugin so you don't have any issues with the normal netbox functionality.

**Comment by DonMusto** [comment]
> > Hi there, I just installed NetBox 3.0.1 and get the following error, is it related?
> > <class 'django.template.exceptions.TemplateDoesNotExist'>
> > base.html
> > Python version: 3.9.6
> > NetBox version: 3.0.1
> 
> Yes, the plugin has not been updated to support the 3.0 release of netbox.
> For now it would be best to uninstall the plugin so you don't have any issues with the normal netbox functionality.

Okay, thanks. I'll do that for the time being and look forward to the forthcoming update!

**Comment by Bennekom** [comment]
Hello Mattieserver

After some time trail and error, was the plugin installed. What needs to be added to the installation steps is:

After installing
"sudo systemctl restart netbox netbox-rq"

What results at this time, in error base.html not found.

"Server Error
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'django.template.exceptions.TemplateDoesNotExist'>

base.html

Python version: 3.8.10
NetBox version: 3.0.10"


Can you please share your progress, when will the updated version be ready?

**Comment by spoon1331** [comment]
Just wondering if there is any update on this one, as I would love to deploy into our netbox 3.0.10 environment?

**Comment by nemmeviu** [comment]
+1

**Comment by Flocon29** [comment]
+1

**Comment by mattieserver** [comment]
Support for netbox 3.1 was added, use version [v1.0.0](https://github.com/mattieserver/netbox-topology-views/releases/tag/v1.0.0)
