### ISSUE TITLE
Increase cable maximum cable length

### ISSUE THREAD

**Issue by tkeeler42** [mattieserver/netbox-topology-views#75]

**Comment by tkeeler42** [comment]
Currently the maximum cable length is 32767, please raise the maximum to a value over 75000. 
![cable length](https://user-images.githubusercontent.com/89475232/130655721-28be4272-7d51-4b29-bacb-6a4501d5b224.jpg)

**Comment by mattieserver** [comment]
Hi,

This is not a limit from the plugin.
If you want this changed you will have to open a request/issue in the actual netbox repository.
