### ISSUE TITLE
Search by tag

### ISSUE THREAD

**Issue by networkpadawan** [mattieserver/netbox-topology-views#8]
first of all great plugin! 
would like to know if its possible to add the option to query by tag?

**Comment by mattieserver** [comment]
I did a quick check and it should be possible.
I will look into implementing this.

Do you want the option to preload certain tags? Like with the device-roles?

**Comment by networkpadawan** [comment]
that would even be better, having the option to search is great but having a preload would be even better (we have some devices that are on inventory or still not with circuits loaded into netbox so a tag can filter those out)
