### ISSUE TITLE
Error when devices are connected to power feeds

### ISSUE THREAD

**Issue by joaolucasmacedo** [mattieserver/netbox-topology-views#80]
If any device selected to a topology is connected to a power feed it shows "something went wrong".
Maybe there is a way to represent power feeds on a topology or at least remove whatever is causing the problem.

**Comment by joaolucasmacedo** [comment]
Just updating to remind you that maybe it is simple to remove anything regarding devices and power feeds.

**Comment by joaolucasmacedo** [comment]
Just for remember @mattieserver that classic problem when devices are conected do power feeds. It is still there.

**Comment by mattieserver** [comment]
Hi,

I will add support for this in the next release (so for netbox v3.3)
