### ISSUE TITLE
Error after installation: django.template.exceptions.TemplateDoesNotExist

### ISSUE THREAD

**Issue by PaterRod** [mattieserver/netbox-topology-views#84]
Hello,

I installed the plugin in my netbox 3.1.8, but when I try to open "Topology" from the plugin tab, I get this error:
```
Server Error
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'django.template.exceptions.TemplateDoesNotExist'>

base.html

Python version: 3.9.2
NetBox version: 3.1.8
If further assistance is required, please post to the [NetBox discussion forum](https://github.com/netbox-community/netbox/discussions) on GitHub.
```

Any idea to this?

Regards

**Comment by mattieserver** [comment]
Hi,

What version of the plugin did you use?
You might need to specify the version with `pip install netbox-topology-views==1.0.0a7`

Or add ` netbox-topology-views==1.0.0a7` to the local_requirements.txt file.

**Comment by PaterRod** [comment]
Thank you for your quick support. Pip installed an old version 0.5.xx
With the 1.0.0a7 it is working very well!

Thanks!
