### ISSUE TITLE
Access Switch errord filters

### ISSUE THREAD

**Issue by SerhiiZahuba** [mattieserver/netbox-topology-views#85]
There is an error after updating the tool. If I select Access Switch in the "Device Role" filter, then I get an error.

<class 'AttributeError'>

'Interface' object has no attribute 'circuit'

netbox v3.1.8
netbox-topology-views 1.0.0

**Comment by mattieserver** [comment]
Hi,

I believe i know what causes the issue, i will try to create a new release tomorrow.

**Comment by mattieserver** [comment]
Was fixed in v1.0.1
