### ISSUE TITLE
Error building topology.

### ISSUE THREAD

**Issue by ekrichbaum** [mattieserver/netbox-topology-views#86]
<class 'AttributeError'>

'Interface' object has no attribute 'circuit'

Python version: 3.10.2
NetBox version: 3.1.9

Just installed this today and started adding to it. One of my sites has 2 circuit teminations and when added generates the above error. Sites without those circuits seem to work fine.

**Comment by ekrichbaum** [comment]
[https://github.com/mattieserver/netbox-topology-views/issues/85](url)

Seems to be the same as this one.  Sorry for the extra noise.

**Comment by mattieserver** [comment]
Hi,

I believe i know what causes the issue, i will try to create a new release tomorrow.

**Comment by ekrichbaum** [comment]
Patch does eliminate the error.  No matter the setting "'enable_circuit_terminations': True" or False, the error does not occur. I don't see any additional elements for those circuits which may be the suspected behaviour. What would be nice is a provider logo with a circuit, maybe, but not necessary for sure.
