### ISSUE TITLE
Feature Request: Dark Mode Support

### ISSUE THREAD

**Issue by ekrichbaum** [mattieserver/netbox-topology-views#89]
Netbox 3.1.9, switching to dark mode renders ok but labels are near black on black (and black cables are as well)

![image](https://user-images.githubusercontent.com/11653069/157542774-8d226df4-a8c3-456b-81be-45a6d52ed7c4.png)

Not sure if the black cables are something fixable except maybe add a slight white/grey border...

Just thoughts.

**Comment by mattieserver** [comment]
The node text was changed in #90 and is available in release v1.0.2.
The black cable color comes from netbox itself so i wont change that.

**Comment by mattieserver** [comment]
![image](https://user-images.githubusercontent.com/3049868/157646562-5e920fd0-796f-44b6-a044-426b97e87407.png)
