### ISSUE TITLE
Feature: Use icon stored in device role

### ISSUE THREAD

**Issue by dreng** [mattieserver/netbox-topology-views#91]
Currently you have to upload icons to the server and name these images according to the device roles. This is a very cumbersome and not very flexible procedure.

I suggest that the images are taken from the device roles of the database. However, this would require netbox itself to get a feature to map icons to device roles. We can create a feature request for netbox if my proposal would be accepted.

**Comment by joaolucasmacedo** [comment]
I have the same problem when upgrading the plugin, and always have to copy my personal device images. 
It would be nice to have other, and permanent, way to store device role images. And if it was a core functionality on NetBox it would be even better.

**Comment by mattieserver** [comment]
Hi,

How do you do the upgrade?
I just tested by pulling a new git release (Option B from https://netbox.readthedocs.io/en/stable/installation/upgrading/). 
The custom images stay in the static/netbox_topology_views/img/ folder.

**Comment by joaolucasmacedo** [comment]
> Hi,
> 
> How do you do the upgrade? I just tested by pulling a new git release (Option B from https://netbox.readthedocs.io/en/stable/installation/upgrading/). The custom images stay in the static/netbox_topology_views/img/ folder.

I use option A. Than on a Netbox upgrade event I install topology-views and copy my custom images after all.

**Comment by dreng** [comment]
As this FR has been addressed in PR #193 I close it now.
