### ISSUE TITLE
Pre-release and 3.2.0 beta

### ISSUE THREAD

**Issue by ekrichbaum** [mattieserver/netbox-topology-views#95]
some sites seem to draw well with the changes. I have 1 site that trips this error.

<class 'AttributeError'>

'CircuitTermination' object has no attribute 'device'

Python version: 3.10.3
NetBox version: 3.2.0-beta2

I'm not finding anything different between these circuit terminations and other that do work off the top. Is there any way to kick debugging up a notch?

**Comment by ekrichbaum** [comment]
Setting        'enable_circuit_terminations': False  does    eliminate that error as well, but I'm curious as to which circuit and where the issue is.

**Comment by ryanmerolle** [comment]
[NetBox 3.2.0](https://github.com/netbox-community/netbox/releases/tag/v3.2.0) was just released and has a number of [extension improvements](https://github.com/netbox-community/netbox/issues/8333).

Furthermore, a [NetBox 3.2 plugin tutorial](https://github.com/netbox-community/netbox-plugin-tutorial) was released

**Comment by dreng** [comment]
@ekrichbaum Is this still an issue with the current version of netbox and netbox-topology-views?

**Comment by ryanmerolle** [comment]
This is an old issue that should have been closed.  Probably best you read the docs.

https://github.com/mattieserver/netbox-topology-views#versions

**Comment by ekrichbaum** [comment]
not an issue any longer.  you can close.
