### ISSUE TITLE
white on white connection lines ;-)

### ISSUE THREAD

**Issue by grinapo** [mattieserver/netbox-topology-views#96]
Maybe #89 was too successful :grin: , now some connections are white-on-white in normal (light) mode.

![flame_2022-04-09_12-23](https://user-images.githubusercontent.com/1056054/162567874-29b4340b-424f-4b96-9f87-073fa21ac8ee.png)

Is there any way to change this without nagging you?

**Comment by mattieserver** [comment]
Line/cable color is taken from netbox itself.
So if you did not actually use a while cable you might want to change that in netbox on the cable properties.

**Comment by grinapo** [comment]
Damn... it _is_ a white cable indeed. I have to process that problem. :-) I have to check the css about the background color...
But I guess it's not a "bug". Thanks.

**Comment by mattieserver** [comment]
I will check if I can add some shadow or something to make it clearer.

**Comment by grinapo** [comment]
that was my solution:
app.css:
`canvas { background-color: #f0e4cd; }`

But probably a shadow (or an underlay thicker line background) would be the best.

**Comment by mattieserver** [comment]
If i add a shadow to the lines it looks like this:
![image](https://user-images.githubusercontent.com/3049868/162733246-6707b184-8f66-4095-aba5-1c8b57908a75.png)

**Comment by ekrichbaum** [comment]
May also want to deal with the opposite (black cables in dark mode).

**Comment by mattieserver** [comment]
I also changed the background color when dark mode is used:
![image](https://user-images.githubusercontent.com/3049868/162742190-0c8ac3ef-241d-4e98-9894-ffa38dde4136.png)

**Comment by grinapo** [comment]
> If i add a shadow to the lines it looks like this:

I think it's great. 

Subtitles on video players usually add a black and a white border as well to the letters so it's visible on both black and white background. But if you handle dark mode sparately with white shadow it could work as well.

**Comment by mattieserver** [comment]
shadow was added and background was changed
