### ISSUE TITLE
Typo in default plugin config for storage image

### ISSUE THREAD

**Issue by buzzingbren** [mattieserver/netbox-topology-views#99]
Hi,

The default values for the plugin renders devices with the storage role as an alien. Probably devices with the wan-network role as well.
I haven't got any plugins_config setting configured (yet), this is what my debug output gave me.

{'netbox_topology_views': {'allow_coordinates_saving': False,
                           'device_img': ['access-switch',
                                          'core-switch',
                                          'firewall',
                                          'router',
                                          'distribution-switch',
                                          'backup',
                                    **-->   'storage,wan-network', <---**, missing two apostrophes around the comma
                                          'wireless-ap',
                                          'server',
                                          'internal-switch',
                                          'isp-cpe-material',
                                          'non-racked-devices',
                                          'power-units'],
                           'draw_default_layout': False,
                           'enable_circuit_terminations': False,
                           'ignore_cable_type': ['power outlet', 'power port'],
                           'preselected_device_roles': ['Firewall',
                                                        'Router',
                                                        'Distribution Switch',
                                                        'Core Switch',
                                                        'Internal Switch',
                                                        'Access Switch',
                                                        'Server',
                                                        'Storage',
                                                        'Backup',
                                                        'Wireless AP'],
                           'preselected_tags': []}}

No big issue and easily to resolve by overriding the values in my own configuration.py.

Thanks for the work on this plugin, works like a charm!

Edit update: forgot the used version of netbox-topology-views, this is v1.1.0

**Comment by mattieserver** [comment]
Fix will be in the next release
